### ISSUE TITLE
Higher level support for concurrency / parallelism

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#103]
It should be possible to support this. Will need to support its dependencies first, though:

https://github.com/ktakashi/scheme-concurrent

**Comment by kozross** [comment]
I'm happy to take on adding these (I seem to be on a bit of a roll at the moment with this kinda thing). We also need to have ``thread-join!`` available to us if we are to use scheme-concurrent. 

However, I suspect we might be able to do this better with an in-house solution, possibly based on libck stuff directly, rather than via the SRFIs. Basically, by using scheme-concurrent, we impose three levels of indirection - this library calls into the SRFIs, which then call into the C code (especially for SRFI 18, which is critical for this). If we instead did it under, say ``(scheme cyclone concurrent)``, we can avoid all this kerfuffle, and have 'hot' parts of the code directly in inline C if needs be.

Additionally, thread pools and futures aren't exactly hi-tech anymore: there are better alternatives out there, such as STM (as in Clojure or Haskell), data flow parallelism (as in Haskell, and several other languages too), and lockfree concurrency (as in Rust and D, except with more high-level support). which we can probably support instead. Given that libck has support for *hardware* transactional memory and atomic ops (among *many* other things), these things can also be *blazingly* fast if we want them to be.

**Comment by justinethier** [comment]
You are on a roll :)

I like the idea of a `(scheme cyclone concurrent)` module and am open to ideas here. The key point is the ability to provide higher-level (or at least, built-in) constructs for concurrency than threads and locks, which can be error prone.

Some thoughts off the top of my head:

Shared queues are handy in multitheaded programming and providing them means a user does not have to reinvent the wheel. The implementation should be straightforward - basically use part of the list (and/or vector) API we have and make it work with an internal lock.

Thread pools seem like they could be handy since OS-level threads do have quite a bit of overhead.

I like the idea of lightweight threads, such as Erlang style, in combination with OS-level threads. There is probably a ton of work required for that though (have not looked into it at all). I assume there would have to be some kind of scheduler.

In addition to the above the right answer is likely to start looking at what these other languages are doing. Part of the problem for Cyclone though is immutability - maybe that has to be a requirement for using some of these approaches? IE, maybe we cannot mix mutations with STM, for example? Or not, I haven't spent the time thinking about these things.

It would be good if cyclone enforced immutability for quoted objects. Right now that is not being tracked or enforced. But if it was, an error could also be thrown if a mutable object was used by a construct where it is not allowed. One more point to consider.

**Comment by kozross** [comment]
Those are fair points - allow me to respond.

Basically, shared queues and thread pools are only a small layer of abstraction above OS-level threads. My whole point was simply that we can (and in my opinion, *should*) do better than this, as other languages already are. From the point of view of concurrency and parallelism, we should focus on a much more declarative approach than these require (*especially* for parallelism IMHO). Immutability is kind of a concern, but at the same time, it can be worked around - Clojure does this fine, despite being built atop of Java, which gives such flimsy immutability guarantees that it isn't even worth calling them such.

Essentially, for ``(scheme cyclone concurrent)``, I think the following are essential:

- Some built-in data parallelism constructs ([this][1] is a good description of what I mean). Essentially, the user would write code dictating to Scheme what has to occur before what, which would then allow it to do work in parallel such that it does not conflict with it.
- High-level parallelism primitives (``pmap`` and ``p-vector-map`` would both be good examples of that). Essentially, it would allow you to replace instances of sequence-processing instructions (such as ``map`` and ``vector-map``) with their parallel equivalents easily and without having to worry about fiddling with the threads (in whatever form) necessary to make it happen. I believe Guile already has such things.
- STM (probably using something like the Clojure trifecta of [agent][2], [atom][3] and [ref][4]) . The links provide very good descriptions of the semantics that these grant.

This is all user-visible stuff - as you can see, I'm driving for a level of concurrency and parallelism where explicit management of threads by the person actually writing Scheme code is totally unnecessary. Instead, we give users a bunch of very high-level constructs, which they can use directly to do whatever they need to do.

In terms of how we *implement* this, it can be done on top of some form of thread pooling (which is how it's done by Haskell and Clojure *definitely* - I'm not sure about other languages). I would recommend looking at Guile's [Fibers][5] - Andy's work is using some pretty hot research, and is quite heavily inspired by Erlang. We could even provide direct access to this system to people who want to mess with stuff at a lever 'lower' than ``(scheme cyclone concurrent)``, but don't wanna monkey with SRFI 18 threads directly.

[1]: http://hackage.haskell.org/package/monad-par-0.3.4.8/docs/Control-Monad-Par.html
[2]: https://clojure.org/reference/agents
[3]: https://clojure.org/reference/atoms
[4]: https://clojure.org/reference/refs
[5]: https://github.com/wingo/fibers

**Comment by justinethier** [comment]
From our discussion earlier, here is your link to Andy's post about Guile fibers:
https://wingolog.org/archives/2016/10/12/an-incomplete-history-of-language-facilities-for-concurrency

This is another, specifically in reference to goroutines: https://wingolog.org/archives/2016/09/20/concurrent-ml-versus-go

**Comment by justinethier** [comment]
See also:
https://en.wikipedia.org/wiki/Concurrent_ML
