### ISSUE TITLE
Threading issues with parameter objects

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#109]
From the R7RS:

> If an implementation supports multiple threads of execution, then `parameterize` must not change the associated values of any parameters in any thread other than the current thread and threads created inside `{body}`.

**Comment by justinethier** [comment]
If user code could differentiate between threads, then perhaps `make-parameter` could be modified to take care of this. Unfortunately it may need to be more than just a lookup against `current-thread`, since the above from r7rs implies child threads should (can?) inherit their parent's parameters.

**Comment by justinethier** [comment]
There is a `thread-params-dev` development branch for this. The code partially works, and is using the thread data object to store params, but is not yet handing off thread params when creating a new thread.

**Comment by arthurmaciel** [comment]
Chibi uses a cond-expand to check whether threads are at play. However I don't know how it is implemented.

https://github.com/ashinn/chibi-scheme/blob/master/lib/srfi/39.sld
https://github.com/ashinn/chibi-scheme/blob/master/lib/srfi/39/param.c
https://github.com/ashinn/chibi-scheme/blob/master/lib/srfi/39/syntax.scm
https://github.com/ashinn/chibi-scheme/blob/master/lib/srfi/39/syntax-no-threads.scm

**Comment by justinethier** [comment]
Chibi has compile-time options for several features including threads. It doesn't make as much sense for Cyclone do to this however since our GC is multithreaded, so threads are always necessary for the runtime.

**Comment by justinethier** [comment]
Getting intermittent errors when running the following benchmarks on this branch: dynamic, slatex, wc

For example:

Running slatex:500
Error: Invalid type: expected pair, found : #\q
Call history:
scheme/base.sld:Cyc-bin-op-char
scheme/base.sld:Cyc-bin-op
scheme/base.sld:char=?
scheme/base.sld:Cyc-bin-op-char
scheme/base.sld:Cyc-bin-op
scheme/base.sld:char=?
scheme/base.sld:Cyc-bin-op-char
scheme/base.sld:Cyc-bin-op
scheme/write.sld:display

**Comment by justinethier** [comment]
The above errors are fixed with https://github.com/justinethier/cyclone/commit/3f75e8d231f3bafbe737c46f8d3777be97416f76

**Comment by justinethier** [comment]
This is fixed and has been merged back to master for the 0.4.1 release.
