### ISSUE TITLE
Support +inf.0 and -inf.0

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#112]
The reader should be able to recognize these values.

Under the hood, may need to use C99 or gcc macros that may be non-portable to support this, though.

**Comment by lluixhi** [comment]
You can use the C99 definition in `math.h`: `INFINITY`
You can also use `__builtin_inff()` on Clang and GCC > 3.3

I guess the rest depends on what compilers you plan to support..

**Comment by justinethier** [comment]
@lluixhi  - Thanks, I will try to find some time for this as part of 0.2.1. Most likely using C99 definitions.

**Comment by justinethier** [comment]
Can compute `inf`, EG:

    (expt 2 10000000000)

**Comment by justinethier** [comment]
http://stackoverflow.com/questions/7212356/how-to-produce-a-nan-float-in-c

**Comment by justinethier** [comment]
Need to have the compiler check for these values during constant folding, and reject the fold if either value is produced.

**Comment by justinethier** [comment]
This has been added, as well as support for `nan` constants.
