### ISSUE TITLE
Threading - mutex-state

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#118]
Consider adding support for both these functions. 

See: http://srfi.schemers.org/srfi-18/srfi-18.html

**Comment by justinethier** [comment]
As part of `mutex-state`, would probably also want to add support for optional arguments to `mutex-lock!`:

    (mutex-lock! mutex [timeout [thread]])

**Comment by arthurmaciel** [comment]
@justinethier, is this still relevant?

**Comment by justinethier** [comment]
We are good on this, closing.
