### ISSUE TITLE
Library init dependencies

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#120]
It may be necessary to explicitly detect dependencies when generating library init code. Right now it is possible to write libraries such that defined functions may call other functions before they are initialized. The workaround right now is to ensure everything is defined before it is used, but if a failure occurs the program segfaults during initialization with no indication of the problem. Cyclone will likely need to to better.

A good example of the problem is SRFI 128, if the order of the `include` directives is reversed.

**Comment by arthurmaciel** [comment]
@justinethier, is this issue still relevant?

**Comment by justinethier** [comment]
@arthurmaciel I don't think so, I tried to recreate the original issue with srfi 128 and could not reproduce. This may have been fixed by modifications made to ensure dependencies are always properly resolved. Let me close this one out; we can revisit later if there are specific issues with library initialization.
