### ISSUE TITLE
Bignum support

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#140]
Cyclone does not support bignums. 

See `pi.scm` benchmark for an example.

**Comment by kozross** [comment]
[LibTomMath][1] seems like a good option to provide this support - it's well-maintained, has pretty much everything we'd want, and is licensed under the WTFPL, which means no conflicts with the license of this project. It's also recently (ish) had a 1.0 release, which gives me further confidence of its suitability.

[1]: http://www.libtom.net/LibTomMath/

**Comment by justinethier** [comment]
Cool, thanks for the tip, I'll need to spend some time looking into this further. Overall the goal has been to avoid third party dependencies whenever possible, but bignums are a good candidate for an external library.

**Comment by kozross** [comment]
In the case of bignums, I think a third-party dependency is OK - Cyclone is meant to be efficient, and reinventing the wheel for stuff like this doesn't seem the best way to achieve it. Plus, LibTomMath is well-maintained, and hardly seems like a huge dependency anyway.

**Comment by justinethier** [comment]
See also http://www.more-magic.net/posts/numeric-tower-part-1.html - although none of that is necessarily applicable to Cyclone.

**Comment by justinethier** [comment]
There is also GMP but I don't know anything about it other than it is widely used and fast: https://gmplib.org/ 

See http://gambitscheme.org/wiki/index.php?title=Benchmarks&oldid=2267

**Comment by kozross** [comment]
There's nothing wrong with GMP, and it is *very* efficient. The main reason I didn't suggest it was the LGPL licensing on it - if this is something you're OK with, then by all means, it's worth using.

**Comment by justinethier** [comment]
According to GMP's [website](https://gmplib.org/#WHAT):

> Since version 6, GMP is distributed under the dual licenses, GNU LGPL v3 and GNU GPL v2. These licenses make the library free to use, share, and improve, and allow you to pass on the result. The GNU licenses give freedoms, but also set firm restrictions on the use with non-free programs.

Regarding GNU's page on [LGPL](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic):

> If you dynamically link against an LGPL'd library already present on the user's computer, you need not convey the library's source. 

Which would be the intended use case for Cyclone.

There is also [this discussion](http://answers.google.com/answers/threadview/id/439136.html) which might be applicable if someone decided to use Cyclone for a commercial project:

> Q2b: What is the implication of dynamic linking?
> A2b: That is pretty much up to you. You can decide to...
>  - build the application (with your copies of the library),
distribute that application without the library and expect to have
users provide their own copy of the library. In this case - YOU are
not distributing the LGPL library and thus are not bound by the
distribution terms of the LGPL license.

So from what I understand, if we use GMP under the LGPL then Cyclone can remain MIT licensed and there are no additional restrictions as long as we are not distributing GMP along with Cyclone. This will be the case on Linux, as well as presumably Mac OS X and BSD. Windows might be a different story as it may be necessary to deploy a version of libgmp there but Cyclone does not work on Windows yet, so this is a lesser concern at this time.

For what its worth, Cyclone's current MIT license is compatible with GPL:
- https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses
- https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL

So (please correct me if this is wrong) I think GMP's licensing is not an issue and will not require any licensing changes to this project. Longer-term if there ever is a Windows version of Cyclone it may be possible to either revisit GMP licensing at that time or just disable bignums on that platform and not include GMP at all.

**Comment by kozross** [comment]
Well, I have no issue with the LGPL personally - I was merely unsure if you had any. If you're OK with it, then GMP is about the best-performing bignum lib I know.

**Comment by justinethier** [comment]
@kozross - Thanks. Having read up on it, I think I am OK with it in this instance.

**Comment by justinethier** [comment]
Hmm... http://lists.gnu.org/archive/html/chicken-users/2009-10/msg00011.html

**Comment by kozross** [comment]
All of those concerns are valid, and one of the reasons why I suggested LibTomMath in the first place. I favour it over alternatives for the following reasons:

- Simplicity (it does just what it needs to do and nothing more)
- Stability (it's had a 1.0 release for a while, and gets used in projects like LibreOffice, which wouldn't use something unstable)
- Compactness (smaller libraries are easier to learn, less likely to have issues, and generally make me happy inside)

In the absence of any strong preference to anything (license aside), I would again recommend LibTomMath for our use. Additionally, investigating further, there is also [TomsFastMath][1], which does all that, but even faster, and doesn't even use the heap. It will mean that we won't get arbitrary-precision decimals built-in (but we weren't that concerned about this anyway) and that rational numbers *might* have to be implemented by us in-house (although there's considerable facilities to support this in those libraries anyway, even if they don't have it exactly), but I believe it should be both efficient and non-problematic license-wise.

[1]: http://www.libtom.net/TomsFastMath/

**Comment by justinethier** [comment]
:+1: 

Let me start by taking a look at the main LibTomMath library since it already comes with most distros.

**Comment by kozross** [comment]
Upon further investigation, it seems like TomsFastMath isn't really appropriate for our needs - it's designed for high-performance crypto primitives, and thus has to work to an (admittedly arbitrary) bound, instead of being a true bignum implementation. Thus, the main LibTomMath is pretty much our go-to choice in this case.

**Comment by justinethier** [comment]
This page has some good tips for a bignum integration:

http://www.tcl.tk/cgi-bin/tct/tip/237.html

**Comment by kozross** [comment]
I will have a read. Also, yay, happy to see branch work on bignums!

**Comment by justinethier** [comment]
Saving for later, this program does not compile yet:

    (import (scheme base) (scheme write))
    (write 
      (= 999999999999999999 9999999999999999999))

**Comment by justinethier** [comment]
Bignums are easy to integrate into the major GC, but, this does not account for any bignums that are left on the stack during minor GC. Unfortunately bignums abandoned on the stack will leak memory. One possible solution is to allocate all bignums directly on the heap, and this is the first approach we will try. This work will need to be done on a separate branch so it is possible to measure the performance impact.

**Comment by kozross** [comment]
If LibTomMath bignums are anything like GMP ones, I think that we'll have to allocate them on the heap, as they employ variable-length arrays as 'limbs' for the number. I believe this approach is quite common, and that these libraries heap-allocate anyway, so we probably can't help but take that performance penalty.

I don't think this is a big issue - since we'll be providing SRFI 143 for fixnum ops on top of the original ones, if people need to go fast and know they're not gonna hit bignum boundaries (or don't care about overflow/underflow if they do), they have those operations to fall back on.

**Comment by justinethier** [comment]
Yeah, I think this will be manageable. Cyclone already allocates mutex and condition variable types directly on its major GC heap so it shouldn't be too bad. Will just need to go through and account for everything that uses a flavor of `mp_init` to prevent leaks.

By the way, the pi benchmark passes now. On the other hand some of the SRFI 60 tests are blowing up. There's still plenty of work to be done, but if you want to check it out everything is on the `bignum-dev` branch (both in this repo and cyclone-bootstrap).

I am planning to sketch out SRFI 143 at some point once bignums are in a good place. Feel free to look at it in the meantime if you want. One thing - since this SRFI only needs to target fixnums and should be as fast as possible, it will be best to (for the most part) just write new integer functions for it. The existing ones have too many dependencies on other types (doubles, boxed ints, etc).

**Comment by kozross** [comment]
Excellent news! Does this mean that bignums are 'ready', or are you still in the process of implementing them? If so, I basically would need to know two things:

- How do I test if an ``obj`` is a bignum?
- How do I unpack an ``obj`` into a bignum?
- What do I need to call to turn a bignum back into an ``obj``?

**Comment by justinethier** [comment]
They aren't ready to be merged back to master yet, but hopefully soon. There is a new `bignum2-dev` branch you can use if you want to test out the latest changes.

To answer your questions:

- There is a `(bignum? obj)` predicate to test for bignums
- Bignum is an object: https://github.com/justinethier/cyclone/blob/bignum2-dev/include/cyclone/types.h#L364 - although you need to allocate them using the `alloc_bignum` macro. What type of conversions did you have in mind?

**Comment by kozross** [comment]
A lot of SRFI 60 is of the form 'convert arguments to ``int`` in C code, do C bitwise ops on them, convert back to ``obj`` and return'. Obviously now, it'd have to be more like:

1. Check if argument(s) are bignums - if they are, unpack to bignums where needed, do stuff, return a bignum.
2. Check for overflow - if it's there, unpack into bignums, do stuff, return a bignum.
3. Otherwise, as above.

**Comment by justinethier** [comment]
Sure. If you get a bignum you would need to use LibTomMath to work with the `mp_int` directly to do the necessary operations. There are some examples in `runtime.c` of working with fixnums and bignums. For example you can take a look at [`Cyc_expt`](https://github.com/justinethier/cyclone/blob/bignum2-dev/runtime.c#L3144). 

You can use `&bignum_value()` to directly access the bignum object's `mp_int`.

If a function receives both a fixnum and bignum argument the integer and result are being cast to a bignum. Bignums are cast to doubles if there are bignum/double arguments, but that is probably not needed for SRFI 60.

**Comment by justinethier** [comment]
I think bignums are ready to go. Everything has been merged back into master and this is slated to be part of the upcoming 0.4 release.

**Comment by justinethier** [comment]
Closing per previous comment.
