### ISSUE TITLE
thread-join! not exported for SRFI 18

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#150]
I saw this from a compiler error, and checking the API page, it doesn't appear to be there either. This makes the whole implementation of SRFI-18 very hard to use (threads can't wait for each other to finish).

**Comment by justinethier** [comment]
Thanks for reporting this. I agree `thread-join!` should be implemented, let me take another look at making that happen.

**Comment by justinethier** [comment]
Some of this was added last week but unfortunately a complete change is more complicated than I anticipated, as threads are currently detached after they are created, which causes pthread_join to fail.

In the meantime there is a workaround in https://github.com/justinethier/cyclone/blob/master/examples/threading/thread-join.scm

**Comment by justinethier** [comment]
`thread-join!` is included in 0.5.3
