### ISSUE TITLE
No support for import in icyc

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#151]
Just tested this, by doing the following in an ``icyc`` REPL:
```
(import (srfi 111))
```
This gave me the following error message:
```
Error: Unbound variable: import
```

Am I missing something, or does ``icyc`` not support importing libraries?

**Comment by justinethier** [comment]
Thanks for the feedback, @kozross.

Unfortunately `import` is not supported yet, there are larger changes that need to be made first. See: https://github.com/justinethier/cyclone/issues/87

**Comment by justinethier** [comment]
Closing this as a duplicate of #87.
