### ISSUE TITLE
Importing SRFI-8 causes a compiler failure

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#152]
While it is a documented thing that SRFI-8 is built into Cyclone, this seems a strange thing for the compiler to break on. Would it be possible for imports of SRFI-8 to get translated to no-ops?

**Comment by justinethier** [comment]
Thanks for reporting this - I updated the documentation a bit to try and avoid confusion.  

There is no `(srfi 8)` library so throwing an error is reasonable. Also keep in mind that changing it to a no-op would still not prevent an error if `(scheme base)` is not also imported.
