### ISSUE TITLE
Build error when compiling project

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#153]
Error is as follows:

```
srfi/18.c: In function ‘__lambda_20’:
srfi/18.c:607:24: error: ‘gc_thread_data {aka struct gc_thread_data_t}’ has no member named ‘thread_id’; did you mean ‘thread_state’?
         pthread_join(td->thread_id, NULL);
```

**Comment by justinethier** [comment]
Sorry about that. There is a chicken-and-egg problem here - `thread_id` is a new field in `types.h` so an older version of Cyclone cannot compile it. You need to compile `(srfi 18)` with the latest [cyclone-bootstrap](https://github.com/justinethier/cyclone-bootstrap) from master.

**Comment by kozross** [comment]
Reopening this, as this error persists, even from cyclone-bootstrap head:

```
../cyclone-bootstrap/cyclone -A . srfi/18.sld
srfi/18.c: In function ‘__lambda_37’:
srfi/18.c:436:49: error: ‘gc_thread_data {aka struct gc_thread_data_t}’ has no member named ‘heap’
         cond = gc_alloc(((gc_thread_data *)data)->heap, sizeof(cond_var_type), (char *)(&tmp), (gc_thread_data *)data, &heap_grown);
                                                 ^~
srfi/18.c: In function ‘__lambda_29’:
srfi/18.c:531:49: error: ‘gc_thread_data {aka struct gc_thread_data_t}’ has no member named ‘heap’
         lock = gc_alloc(((gc_thread_data *)data)->heap, sizeof(mutex_type), (char *)(&tmp), (gc_thread_data *)data, &heap_grown);
                                                 ^~
```

**Comment by justinethier** [comment]
It looks like you are pulling in an older header from the cyclone system installation (?). It may be necessary to be able to specify alternate C header locations.

**Comment by kozross** [comment]
I think this is a very useful capability to have, if we could. It'd make in-tree testing doable (it's not currently).

**Comment by justinethier** [comment]
For reference: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#Directory-Options

**Comment by justinethier** [comment]
Added `-CP`, `-CE`, and `-CL` command line options to specify the C command line when compiling various types of C files. The changelog or cyclone built-in help has details on each option.

For example to use the local directory:

    ./cyclone  -CP "cc ~src-file~ -O2 -Wall -Iinclude -L. -c -o ~exec-file~.o" icyc.scm

The easiest way to build these C compiler commands is to take them from `Makefile.config` and customize as needed.

**Comment by kozross** [comment]
Awesome, thank you!
