### ISSUE TITLE
cond-expand does not appear to work outside of a library

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#154]
Here is a minimum example that reproduces this behaviour:

```
(cond-expand
  (chibi (import (chibi test)))
  (cyclone (import (scheme cyclone test))))
```

If you try to compile this (filename in this case is ``sample.scm``), ``cyclone`` produces the following error message:

```
Error: Unbound variable(s): (cyclone import scheme test) 
Call history:
scheme/cyclone/transforms.sld:built-in-syms
scheme/cyclone/transforms.sld:difference
scheme/cyclone/transforms.sld:remove
scheme/cyclone/transforms.sld:difference
scheme/cyclone/transforms.sld:remove
scheme/cyclone/transforms.sld:difference
scheme/base.sld:list
scheme/base.sld:error
scheme/base.sld:raise
```

I never got this behaviour if I used ``cond-expand`` inside of a ``define-library`` form. Am I misunderstanding its use, or is this a bug?

**Comment by justinethier** [comment]
Thanks for the bug report. As far as I know `cond-expand` works everywhere except when wrapping `import` statements at the top level, such as in your example above. Cyclone needs to be more robust in this aspect but it is not a quick change.

For example this works fine:

    (import (scheme base) (scheme write))
    (cond-expand
      (cyclone (write "cyclone"))
      (else (write "other")))

**Comment by justinethier** [comment]
`cond-expand` can now be used for program import declarations.
