### ISSUE TITLE
equals? does not compare bytevectors correctly

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#155]
Demonstration code:

```
(define x #u8(1 2 0))
(define y #u8(1 2 0))
(display (equal? x y))
```

According to R7RS-small (as confirmed by Chibi Scheme), this should print ``#t``, but instead prints ``#f``. This appears to be because bytevectors are not deep-compared (as ``equal`` requires). I can confirm this with the following test, which prints ``#t`` as expected:

```
(define x #u8(1 2 0))
(display (equal? x x))
```

**Comment by justinethier** [comment]
Great catch @kozross - thanks for reporting this :+1:
