### ISSUE TITLE
Error: ("Bad argument type" 7 128) - what does this mean?

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#156]
I'm getting the above error from a program that runs successfully under Chibi Scheme. What does this error mean exactly?

**Comment by justinethier** [comment]
It means one or more of the arguments `7` and `128` were of the wrong type. Did you get a call trace or anything to point you to the function that raised this error?

**Comment by kozross** [comment]
The call history is thus:

```
Call history:
srfi/27.sld:make-random-source
srfi/27.sld:random-source-pseudo-randomize!
srfi/27.sld:random-source-state-set!
srfi/27.sld:random-source-make-integers
scheme/write.sld:display
scheme/base.sld:newline
scheme/base.sld:write-char
scheme/base.sld:modulo
./koz/table.sld:make-random
```
``make-random`` is here:

```
    (define (make-random ats frac seed)
      (define bit-count (<< 1 ats))
      (define set-bits (* frac (>> bit-count 3)))
      (make-table (bf-randomly-seeded bit-count set-bits seed) ats))
```

The call that triggers this clearly comes from the following, in a different file:

```
(define t (make-random 10 7 (rng 42))
```
where ``rng`` is a procedure created by SRFI 27's ``random-source-make-integers``. The 128 in this case is clearly ``bit-count``, while the 7 must be the ``frac`` argument. Either way, I cannot understand what the issue is, as in both places where it gets used, the values are of the correct type. For clarity, here is ``bf-randomly-seeded``:

```
(define (bf-randomly-seeded n m seed)
      (do
        ((rng (seed->int-rng seed))
         (bf (bf-new n))
         (i 0 (++ i)))
        ((= i m) bf)
        (bf-set! bf (nth-0 bf 0 (rng (- n i)) 0))))
```
The ``n`` argument is only passed to a procedure which, once again, only uses it as a number. This is part of my confusion at the error message - it doesn't seem to correctly localize where the issue actually took place.

**Comment by justinethier** [comment]
It almost looks like it's in `(define set-bits (* frac (>> bit-count 3)))` since that explains both parameters. We know `7` is the number `7` since it was passed in. What is the definition of `>>`?

**Comment by kozross** [comment]
The definition of ``>>`` is as follows:

```
(define-c 
          >>
          "(void* data, int argc, closure _, object k, object x, object y)"
          "Cyc_check_int(data, x);
          Cyc_check_int(data, y);
          int x_p = unbox_number(x);
          int y_p = unbox_number(y);
          make_int(result, ((x_p) >> (y_p)));
          return_closcall1(data, k, &result);"))
```

**Comment by justinethier** [comment]
Heap allocated integers are deprecated but unfortunately there is still code for them in the C API that needs to be cleaned up. The following works fine with immediate ints:

    (define-c >>
          "(void* data, int argc, closure _, object k, object x, object y)"
          "Cyc_check_int(data, x);
          Cyc_check_int(data, y);
          int x_p = unbox_number(x);
          int y_p = unbox_number(y);
          int result = ((x_p) >> (y_p));
          return_closcall1(data, k, obj_int2obj(result));")

**Comment by justinethier** [comment]
@kozross - No problem, sorry about that. Completely agree about #71. The documentation for the Scheme API is getting there but the C documentation is almost nonexistent right now.

**Comment by justinethier** [comment]
Closing this issue out, there are separate issues now to write the proper documentation.
