### ISSUE TITLE
GC: unexpected object type 16 for object 0x7fa7b932d080 - what does this mean?

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#157]
Once again, Chibi executes this program fine. How should I interpret the above message, and what kind of issue am I looking for?

**Comment by justinethier** [comment]
It literally means the minor GC found a `primitive_tag` during collection. After startup this type is never allocated on the stack/heap by the Cyclone runtime, so the GC does not support it.

Do you get the same error every time you run your program? There might be an FFI function that is causing trouble.

**Comment by kozross** [comment]
It seems I'm having trouble reproducing this now, despite doing the same things I was before. I'm gonna close this for now, but if I track it down again, I will reopen.

**Comment by kozross** [comment]
OK, seems like I was just a bit careless. The cause is the following function (again):

```
(define t (make-random 23 7 42))
```
where ``make-random`` is

```
(define (make-random ats frac seed)
      (define bit-count (<< 1 ats))
      (define set-bits (* frac (>> bit-count 3)))
      (make-table (bf-randomly-seeded bit-count set-bits seed) ats))
```

This makes use of several FFI functions (which have been involved in #156, and were corrected as per your suggestion). The actual problem seems to occur inside of ``bf-randomly-seeded``, which is defined as:

```
(define (bf-randomly-seeded n m seed)

      (define rng (seed->int-rng seed))
      
      (define blocked
        (receive (block off) (indices m)
                 (let ((base (bf-new n))
                       (final (-- (<< 1 off))))
                   (do
                     ((i 0 (++ i)))
                     ((= i block) (begin
                                    (bytevector-u8-set! base block final)
                                    base))
                     (bytevector-u8-set! base i 255)))))
      
      (define (swap! i j)
        (define ib (bf-get blocked i))
        (define jb (bf-get blocked j))
        (cond
          ((= ib jb))
          ((= ib 1) 
           (bf-clear! blocked i)
           (bf-set! blocked j))
          (else 
            (bf-set! blocked i)
            (bf-clear! blocked j))))
      
      (do
        ((i 0 (++ i)))
        ((= i (- n 2)) blocked)
        (swap! i (+ i (rng (- n i))))))
```

In particular, ``bf-set!``, ``bf-get`` and ``bf-clear!`` make use of FFI operations. I've attached the file containing all of them (as it's easier than retyping).
[ffi-code-file.zip](https://github.com/justinethier/cyclone/files/733417/ffi-code-file.zip)

**Comment by justinethier** [comment]
The file contains `bitwise.sld` but I don't see:

    (++ -- bf-clear! bf-get bf-new bf-set! indices seed->int-rng)

**Comment by kozross** [comment]
Sorry about that - I've attached all relevant source files to this. ``(++ --)`` are in ``utilities.sld``, ``seed->int-rng`` is in ``rng.sld``, and everything else is in ``bitfield.sld``.
[files.zip](https://github.com/justinethier/cyclone/files/733572/files.zip)

**Comment by justinethier** [comment]
The problem was the runtime was allocating large bytevectors on the stack which corrupted objects in memory. It's interesting this crashed with the same error all the time on both our systems. Anyway, its fixed now on master.

**Comment by justinethier** [comment]
This doesn't mean much if your program doesn't work, but Cyclone had a decent speedup compared to Chibi. Maybe not as much as I would have hoped but then again these timings were done on an *old* machine:

    justin@justin-desktop:~/temp$ time chibi-scheme prog.scm
    23
    real    3m5.880s
    user    3m5.120s
    sys     0m0.116s
    justin@justin-desktop:~/temp$ cyclone prog.scm
    justin@justin-desktop:~/temp$ time ./prog
    (bf-randomly-seeded 8388608 7340032 42)23
    real    1m7.268s
    user    1m7.228s
    sys     0m0.060s

**Comment by kozross** [comment]
My current tests (I always cross-check with both for correctness and performance) show a speedup of between 3 and 10 times, depending on what needs doing. The higher values are for more artificial tests (usually thinks like hammering the same operation thousands of times), but 3 or so-fold speedup for a more 'normal' program (insofar as what I'm writing can be considered 'normal').

**Comment by justinethier** [comment]
@kozross - Good to know, thanks. At this time Cyclone tends to be better at optimizing primitives than regular `lambda` functions, so that may explain some of the larger speedups you are seeing. 

Anyway, I appreciate all of your feedback. This is the kind of input needed to keep moving the compiler forward. I hope it hasn't been too painful on your end :)

**Comment by kozross** [comment]
It's been good - I'm actually quite happy to be helping find bugs. I'll try to contribute in a more constructive way as soon as I'm not deadline-crunched and have a better understanding of the codebase of Cyclone. I suspect I'll probably just end up writing documentation or something.

**Comment by justinethier** [comment]
@kozross - Great to hear :+1:. No worries, and thanks again for all your help.

**Comment by justinethier** [comment]
Closing this issue out.
