### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#163]
It would be nice to have a CI server such as Travis CI.

**Comment by kozross** [comment]
Does it need a machine to run on? If that's the case, I have a constantly-up x86_64 machine running an Arch derivative (so thus, no issue with library acess) that we could use for this.

**Comment by justinethier** [comment]
Cool, thanks. I'm not sure what it will take to set this up... Travis CI does mention providing VM's. Feel free if you want to look into this.

**Comment by kozross** [comment]
OK, I took a look at Travis CI's stuff. Near-as-I-can-tell, it basically goes like so:

- The repo owner logs on to Travis (using their Github credentials)
- We write a ``travis.yml`` file specifying what we need to install and run from the repo (including stuff like what compiler to use, etc)
- Every time a commit or PR is made, Travis will do those things and report the result

In terms of library availability, Travis yanks from Ubuntu (using ``apt``). I've checked, and everything we need *seems* to be available (I don't have an Ubuntu machine to check, though). Thus, I think it'd be fairly straightforward. I'm willing to try and put together the necessary pieces as a PR if you're good with it.

**Comment by justinethier** [comment]
@kozross - That sounds great. Cyclone will compile fine on Ubuntu although libck would probably have to be built as well, I don't think it is packaged for most versions of that platform.

**Comment by kozross** [comment]
I've done some searching on this topic, and it seems that libck is packaged for Ubuntu [as of 14.10][1]. The most current Ubuntu is past 16.0, so I don't think that's an issue.

[1]: https://github.com/thejinx0r/node-gdrive-fuse/wiki/Manually-installing-Concurrency-Kit-on-Ubuntu-and-Debian
