### ISSUE TITLE
cyclone should be able to take a flag for alternative library search paths

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#165]
This is *particularly* obnoxious when testing new builds in-tree. As-current, I can't seem to get it to link properly to libraries located outside of the default location ``cyclone`` expects, and having a flag which lets me set its library search path would be *really* beneficial.

**Comment by justinethier** [comment]
Thanks, this is a good idea. I think this is mostly a problem for developing internal libraries `(scheme ...)` or `(srfi ...)` as the compiler assumes those are available in the installed location.

There is a workaround that may be "good enough" (but I agree specifying a path is much better) if you use cyclone-bootstrap:

    cyclone$ cyclone srfi/60.sld
    cyclone$ ./sync.sh srfi/60.sld
    cp srfi/60.sld ../cyclone-bootstrap/srfi/60.sld
    cp srfi/60.c ../cyclone-bootstrap/srfi/60.c

    # Change repos and add "srfi/60 " to the Makefile if it is not already there
    cyclone$ cd ../cyclone-bootstrap

    # And either use this line to rebuild everything:
    cyclone-bootstrap$ sudo make clean ; ./install.sh

    # Or just force a rebuild of the bare minimum:
    cyclone-bootstrap$ sudo rm cyclone icyc unit-tests srfi/60.o ; ./install.sh

**Comment by justinethier** [comment]
It should be possible to update `lib:import->filename` to be able to check additional paths. Let me look into this...

**Comment by justinethier** [comment]
This is in progress, there will be 2 new flags based on [SRFI 138](http://srfi.schemers.org/srfi-138/srfi-138.html):

> -A directory
> Append directory to the list of directories that are searched in order to locate imported libraries.
> -I directory
> Prepend directory to the list of directories that are searched in order to locate imported libraries.

**Comment by kozross** [comment]
Makes sense - I'm always happy to support stuff via SRFIs.

**Comment by justinethier** [comment]
@kozross - This has been added and `make test` has been changed to use the locally-built Cyclone libraries instead of relying on anything installed on the system. 

To test, start with a fresh build from cyclone-bootstrap and a test file:

    (import (scheme base) (scheme write) (srfi 60))
    (write (logand 1))

From the cyclone repo:

    justin@justin-desktop:~/Documents/cyclone$ make clean ; make
    justin@justin-desktop:~/Documents/cyclone$ cyclone test.scm
    # no problem so far, but wait:
    cyclone$ sudo rm /usr/local/share/cyclone/srfi/60.*
    justin@justin-desktop:~/Documents/cyclone$ ./cyclone test.scm
    Error: Unable to open file: "/usr/local/share/cyclone/srfi/60.sld"
    # now try again with your local files
    justin@justin-desktop:~/Documents/cyclone$ ./cyclone -A .  test.scm
    justin@justin-desktop:~/Documents/cyclone$ ./test
    1

This is a huge improvement that should simplify development quite a bit going forward. Thanks!
