### ISSUE TITLE
How to add new tests to the makefile's 'make test' recipe?

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#167]
I'm a little unclear on that - from my understanding of make, ``TESTFILES`` should contain everything in ``tests`` with a ``.scm`` suffix. However, my test file called ``srfi-60-test.scm`` doesn't seem to get noticed by this process (it runs the same 109 tests either way). What would I need to change to have it included?

**Comment by justinethier** [comment]
No problem. You can add any test files to `TESTSCM` - for example: 

    TESTSCM = unit-tests srfi-60-tests
