### ISSUE TITLE
UTF-8 support

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#174]
I believe that UTF-8 support is a very necessary thing in this day and age. However, something this involved makes me think self-rolling it looks to be a recipe for disaster. Do you think it'd be OK to depend on a C library that provides this kind of thing?

**Comment by justinethier** [comment]
Some background information on this:

- https://stackoverflow.com/questions/526430/c-programming-how-to-program-for-unicode

- https://github.com/Gumichan01/utf8_string

- http://www.cl.cam.ac.uk/~mgk25/unicode.html

- https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/

**Comment by ararslan** [comment]
If you're alright with depending on an external library, I suggest [utf8proc](https://github.com/JuliaLang/utf8proc), an actively maintained, MIT-licensed, pure C library for processing UTF-8. This powers much of [Julia](https://julialang.org)'s string handling.

**Comment by justinethier** [comment]
@ararslan - Thanks for the suggestion but at the moment support is being added in the `utf8-dev` branch based mostly off the code from http://bjoern.hoehrmann.de/utf-8/decoder/dfa/

Are there any performance comparisons between utf8proc and other libraries/code such as Hoehrmann's decoder?

**Comment by ararslan** [comment]
Ah, my apologies, I didn't realize that UTF-8 support had already been addressed here. I'm not familiar with Hoehrmann's decoder, nor of any existing benchmark comparisons between it and utf8proc.

**Comment by justinethier** [comment]
UTF-8 support has been merged back into `master`. Feedback is welcome...
