### ISSUE TITLE
SRFI 125

### ISSUE THREAD

**Issue by kozross** [justinethier/cyclone#176]
This is an elaboration on my thoughts regarding this, based on stuff raised in #105. Essentially, there are a few issues with SRFI 69 (both interface and reference implementation) that I believe need to be addressed, and I consider SRFI 125 an appropriate framework to do this in. Considering that we need SRFI 125 to be R7RS-large conformant, it seems like a good choice. Additionally, the interface SRFI 125 provides is both more user-friendly *and* more developer-friendly. Lastly, I'm gonna mention exactly what my plan is for SRFI 125 hash tables.

My issues with SRFI 69's interface are basically twofold: it has a very sparse set of operations, not even coming within spitting distance of SRFI 1 for lists or SRFI 133 for vectors; and that its requirements to expose hash functions to the user forces certain choices of algorithms and data structures that are, given modern technology, *at best* rather inefficient. The latter is more of a developer issue, but conformance with the standard forces us down such a path - for example, there's no way to use [cuckoo hashing][1] if the user must be able to have access to the hash function at all times (and with cuckoo hashing, a concept like 'the hash function' is itself meaningless). While there are deprecated backward-compatibility functions that do this in SRFI 125, they're deprecated for a reason, and I see no reason to support them on those grounds.

With respect to SRFI 69's reference implementation, it is a product of another time. A short list of its issues (mostly a refinement of my earlier claims) follows:

- The size limit given for hash tables by default is 2^29 - 3 = 536,870,909, which is bizzarely small. A full hash table of *integers* can fit into the memory of some *phones* nowadays, forget desktop machines. In reality, the size we should be capable of supporting is 2^31 - 1 = 2,147,483,647, which is four times larger.
- As the reference implementation is written with R5RS semantics in mind, the default hashing function handles records about as badly as is possible, hashing every record to the value 1. This will cause the table to degrade to an alist very quickly, except you're also paying a 'hashing' overhead on each operation, and wasting a lot of space, to boot. This was understandable back then, as records weren't part of the core spec, but in this day and age, that's embarassing.
- Symbol hashing is done in just about the worst way possible: by converting the symbol to a string, then hashing that. This essentially makes symbol keys just as slow as string keys, which is extremely odd behaviour and flies in the face of common sense. Once again, the reasons behind this are completely understandable (there's no other way to do it without getting into implementation details), but it's still awful.
- The default implementation of ``hash`` and ``hash-by-identity`` are the same. Given that ``hash-by-identity`` is meant to be used for stuff like symbol keys (mostly), this is *also* quite odd.
- The core hash table data structure used is a *very* poor form of open addressing. Aside from being by far the most complicated algorithm to get right, it is also not really justified by how it performs. There are much better choices (which I will go into later).
- A large number of the operations really should be written in inline C. Hash functions are a perfect example of this: what we're doing is fundamentally quite low-level, and we don't really need the full capability of Scheme. Furthermore, hashing is one of the biggest overheads in a hash table until its size becomes fairly large (a few hundred items in most cases), and bringing that penalty down is definitely something we should do if possible.

Some of the ways in which SRFI 125 improves on this situation: there are far more operations, in-line with SRsFI 1 and 133; hash functions are not exposed to the user directly (instead, SRFI 128 is leaned on for this); and operations from SRFI 69 that would be problematic are deprecated (which means we don't have to implement them, as long as we document this). Additionally, since the implementation will be written for Cyclone and only Cyclone, it'll be easy to fix all the performance concerns above. 

With that in mind, I propose the following:

- [Cuckoo hashing][1], with 3 hash functions, based on a [universal hash function][3] generator.
- Hash functions should be implemented in C where possible.
- Good default hash functions (some of which may require rewrites of SRFI 128 in places), including a default one for records as an extension to the standard.
- A size limit of 2^31 - 1.

These are easy to do (within reason) and quite fast and memory-efficient ([91% load factor is tolerable without excessive collision][2], lookups and deletions are worst-case O(1)). I have sufficient understanding of the algorithms and data structures involved, but I lack some understanding of Cyclone's internals, which is necessary for some of this (particularly hashing). I will use this thread as the place to ask until SRFI 125 has been implemented to our satisfaction.

[1]: https://en.wikipedia.org/wiki/Cuckoo_hashing 
[2]: http://www.eecs.harvard.edu/~michaelm/postscripts/esa2009.pdf
[3]: https://en.wikipedia.org/wiki/Universal_hash_function

**Comment by justinethier** [comment]
Thank you for the list of performance enhancements! Unfortunately I only recently got back to this. Some performance improvements have been made to SRFI 69:

- The size limit is now `2^30 - 1` - this is the largest fixnum limit allowed.
- Records are stored as vectors internally, so they will hash to a value other than `1`.
- Symbol hashing and `hash-by-identity ` have been replaced with a native function.
- Open to suggestions on open addressing. 
- More inlining could still be done.
