### ISSUE TITLE
Allow more than 128 function arguments

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#193]
Right now Scheme functions are limited to a maximum number of arguments. The obvious way to remove this limit is to, instead of passing arguments explicitly, pass them to functions via a C array. This is how CHICKEN passes arguments. Obviously this is a huge change since all function calling conventions would need to be changed, and the compiler would need to compute them in a different way.

This change will probably not happen any time soon, unfortunately. But I am open to input or suggestions in the meantime.

**Comment by bunder** [comment]
BTW, number of allowed arguments was increased to 150 in fbb34302dc024d8ed6b6e83efb812f17316bb901. This issue causes following code to fail: `(apply + (make-list 150 1))`, which seems something limiting.

**Comment by justinethier** [comment]
To follow up on the original comment, in order to properly solve this:

- All functions that never return will need to use a new calling convention. At a minimum they will receive an array of `object` arguments and an integer arg count. This includes both functions in the runtime and compiled functions.
- Functions that do return can keep their existing calling convention. Though, the system will need to know how to properly call into them both at runtime and in compiled code.

**Comment by arthurmaciel** [comment]
AFAIK this is currently the only known Cyclone real limitation. The other Issues are bug related or feature/improvement requests. Am I right?

**Comment by justinethier** [comment]
@arthurmaciel I mean, this is a real limitation that has come up for me at least a couple of times now. How significant of a limitation would you consider this?

**Comment by arthurmaciel** [comment]
@justinethier, I sincerely don't know how it would affect future developers. The only real use case I can think of is `apply` called on a huge list. I recall CHICKEN had a problem with it and, if I am not wrong, the SSAX/SXML code heavily depended on `apply`. I don't know the exact reason why they started (re)using an argument vector. If I am not wrong the performance increased due to that change. However, Cyclone is multi-threaded so I am not sure about the real impact of this change. 

I know this is going to take a lot of work, but I tend to think that the more we wait, the harder is the conversion and the code is more prone to undetected bugs. I know there a lot of priorities and I am sure you are the most clever person to decide if it is worthy the effort :)

**Comment by arthurmaciel** [comment]
@justinethier, I was revising the use of `apply` and found a potential point of problem in `cyclone-winds` source code. As we don't have a built-in markdown parser in core (and we shouldn't), winds generates markdown by string manipulation. According to [this line](https://github.com/cyclone-scheme/cyclone-winds/blob/master/libs/package.sld#L254), if a package has more than 148 dependencies, it wouldn't work. Anyway, 148 dependencies is unrealistic, but just to emphasize that the main concern seems to be with the usage of `apply`.

**Comment by justinethier** [comment]
CHICKEN scheme has a similar problem with regarding to the number of function arguments. They eventually solved the problem at the end of the 4.x series of releases by changing the function calling convention to always receive a vector as one of the arguments, instead of explicitly passing all arguments directly as C arguments. That works, perhaps with some overhead of vector packing/unpacking, but is a massive change. The good news is that it is mostly transparent to user code; if `(cyclone foreign)` is used no changes may even be required to existing applications.

It may be worth doing this in the long-term.

A shorter-term solution could be the previous solution that CHICKEN used. It is possible to use assembly language to take a vector of arguments and place them on the stack so they are passed directly when the function is called. The downside to this approach is that the assembly language is different for each platform. Continuous integration is our friend here but we would be looking at a solution targeting major platforms; probably amd64 / Linux to start.  If a platform is not supported it would need to use our existing code with the 148 argument limit.

**Comment by justinethier** [comment]
See design document `docs/C-Calling-Conventions.md`

**Comment by justinethier** [comment]
This work is nearing completion on the `cargs2-dev` branch.

**Comment by arthurmaciel** [comment]
As a feedback: it works like a charm here!

**Comment by justinethier** [comment]
Great, thanks for the feedback @arthurmaciel !

**Comment by justinethier** [comment]
Alright, this has been merged to `master` for awhile now, and everything seems stable. Can build the compiler, examples, and benchmarks without any problems. Closing.
