### ISSUE TITLE
Library compilation improvements

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#2]
Should detect dependent libraries and build them if necessary. Basically, build them if the .o file does not exist or if it is older than the corresponding source file(s)

**Comment by justinethier** [comment]
This would be nice, but a makefile solves the problem, too. Not sure how important this really is.

**Comment by kozross** [comment]
This *can* be of consequence when at the REPL - especially if you have the standard 'load, play around, change file, reload' kind of workflow REPLs tend to encourage.

**Comment by justinethier** [comment]
Hmm. There is a dependency resolver for working with libraries that could be put to use here. In the meantime the workaround is to use Makefiles.

**Comment by justinethier** [comment]
This is not a recent change but the REPL will detect dependencies during import and load them accordingly.
