### ISSUE TITLE
read-char cannot be called without argument

### ISSUE THREAD

**Issue by wasamasa** [justinethier/cyclone#217]
The standard lists `read-char` with two arities, both with and without argument.  Calling `read-char` without an argument fails however instead of behaving like `read-char` called with `(current-input-port)`.

**Comment by justinethier** [comment]
Thanks for the bug report! Let me look into it...

**Comment by justinethier** [comment]
Great, this comment is right above `Cyc_io_read_char`:

    //  TODO: port arg is optional!

**Comment by justinethier** [comment]
A fix is ready for this on `read-char-dev`. But, I would like to try to find a way to optimize one-argument `read-char` calls in compiled code.

**Comment by wasamasa** [comment]
Same problem goes for `peek-char` BTW.

**Comment by justinethier** [comment]
Good point, just updated for `peek-char`

**Comment by justinethier** [comment]
Fixed in master. Calls with a single port argument will be optimized into primitive calls.
