### ISSUE TITLE
Segfault when allocating huge strings

### ISSUE THREAD

**Issue by wasamasa** [justinethier/cyclone#220]
While trying to debug #219 I noticed that the `make_string` macro uses `alloca` followed by `memcpy` to create a string.  This means that if you run `ulimit -s 500` (roughly the minimum size for the interpreter to boot) followed by `icyc -p '(make-string (* 512 1024) #\x)'`, you'll get a segfault.  CHICKEN reportedly (ab)uses `alloca` as well, but doesn't have this issue.

**Comment by wasamasa** [comment]
Hm, seems like this is a duplicate issue, closing in favor of #81.

**Comment by justinethier** [comment]
Thanks for the report. Re-opening specifically to patch this in `make-string` since that is an easy way to overflow the buffer. The rest can be dealt with under #81 .

**Comment by justinethier** [comment]
Fixed
