### ISSUE TITLE
write doesn't escape quotation marks in strings

### ISSUE THREAD

**Issue by wasamasa** [justinethier/cyclone#221]
> Writes a representation of obj to the given textual output
> port.  Strings that appear in the written representation
> are enclosed in quotation marks, and within those strings
> backslash and quotation mark characters are escaped by
> backslashes. Symbols that contain non-ASCII characters
> are escaped with vertical lines. Character objects are
> written using the #\ notation.

```scm
(write "foo\"bar") ;; "foo\"bar" (Chibi, Kawa, CHICKEN, Gauche, Sagittarius, Foment, Picrin)
(write "foo\"bar") ;; "foo"bar" (Cyclone)
```

edit: Patch:

```diff
@@ static object _Cyc_write(void *data, object x, FILE * port)
       case '\t': fprintf(port, "\\t"); break;
       case '\v': fprintf(port, "\\v"); break;
       case '\\': fprintf(port, "\\\\"); break;
+      case '\"': fprintf(port, "\\\""); break;
       default:
         fputc(*s, port);
         break;
```

**Comment by justinethier** [comment]
Fixed, thanks!
