### ISSUE TITLE
Implement error-object? and friends

### ISSUE THREAD

**Issue by wasamasa** [justinethier/cyclone#225]
I'm currently using the following in my code:

```scm
(cond-expand
 (cyclone
  (define (error-object? x) (and (pair? x) (string? (car x))))
  (define error-object-message car)
  (define error-object-irritants cdr))
 (else))
```

This is far from ideal as it's fragile and relies on an implementation detail of `error`.  I could imagine this to be fixable by implementing `error` in terms of `raise` and an `error-object` record type.  This way you get the predicate and accessors for free and cannot mix an error object up with what the user may raise.  I'm not sure whether this is completely solvable from Scheme or whether you need to adjust the C parts as well.

**Comment by justinethier** [comment]
Thanks for the report, and I agree the right solution is for Cyclone to provide all of this. Let me look into what that would take. 

I suppose the way the C code is raising errors would need to be adjusted for all cases where the condition should appear to be as coming from `error`, which is probably most of the time (EG: type errors, wrong number of args, etc).
