### ISSUE TITLE
Building bootstrap with MSYS2

### ISSUE THREAD

**Issue by steve4444** [justinethier/cyclone#245]
In MSYS2 the build fails. Running `./setup.mysys.sh` gives:

    ...
    cc -shared  -o scheme/base.so scheme/base.o
    scheme/base.o:base.c:(.text+0x36): undefined reference to `find_or_add_symbol'
    scheme/base.o:base.c:(.text+0x36): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `find_or_add_symbol'
    scheme/base.o:base.c:(.text+0x47): undefined reference to `find_or_add_symbol'
    (hundreds of similar errors follows )
    ...
     
    install: cannot stat 'libcyclone.a': No such file or directory
    make: *** [Makefile:84: install] Error 1

**Comment by justinethier** [comment]
How did you invoke this script? 

I would have expected CFLAGS to have specified a local include directory and other required options from [`Makefile.config.msys2`](https://github.com/justinethier/cyclone-bootstrap/blob/master/Makefile.config.msys2).

**Comment by willemhb** [comment]
Getting a similar message in OSX:

`...`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make: ***[scheme/base.so] Error 1`
`...`   
`install: libcyclone.a: No such file or directory`
`make: *** [install] Error 71`

**Comment by justinethier** [comment]
@willemhb - Thanks for the report. That's interesting because there is a Travis CI build for OSX (https://travis-ci.org/justinethier/cyclone). There must be a difference in the environment or such between that build and the setup script.

Unfortunately I do not have a local OSX environment which complicates things a bit...

**Comment by kyoto-shift** [comment]
Same issue here. Tested multiple builds `(0.10, 0.11, 0.11.1, 0.11.2)` using msys64 and msys32 on Windows 8.1, all failed with the same log:

```
cc -shared  -o scheme/base.so scheme/base.o
scheme/base.o:base.c:(.text+0x1): undefined reference to `Cyc_EOF'
scheme/base.o:base.c:(.text+0x2c): undefined reference to `boolean_f'
scheme/base.o:base.c:(.text+0x32): undefined reference to `boolean_t'
scheme/base.o:base.c:(.text+0x62): undefined reference to `find_or_add_symbol'
scheme/base.o:base.c:(.text+0x72): undefined reference to `find_or_add_symbol'
scheme/base.o:base.c:(.text+0x8e): undefined reference to `find_or_add_symbol'
scheme/base.o:base.c:(.text+0x9e): undefined reference to `find_or_add_symbol'
scheme/base.o:base.c:(.text+0xba): undefined reference to `find_or_add_symbol'
[...]
scheme/base.o:base.c:(.text+0x28f09): more undefined references to `Cyc_apply' follow
scheme/base.o:base.c:(.text.unlikely+0x17): undefined reference to `Cyc_invalid_type_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:18: scheme/base.so] Error 1
[...]
install: cannot stat 'libcyclone.a': No such file or directory
make: *** [Makefile:86: install] Error 1
```

I also tried building each dependency manually, that had no discernible effect.

**Comment by justinethier** [comment]
Thanks for the report. There is clearly an issue with MSYS2. I will need to get an environment setup to reproduce locally...

**Comment by kyoto-shift** [comment]
Is there any other information about the build process/log you’d need that’d help out?

**Comment by justinethier** [comment]
@kyoto-shift - Just got a build to work using the latest files on `master`. Can you fetch them and try again?

Note that the sandbox has been removed and everything is installed directly to `/usr/local/`, so cyclone works out-of-the-box.

**Comment by kyoto-shift** [comment]
@justinethier It works! Thanks for the help.

Cloned from `cyclone-bootstrap/master`, installed using a fresh MSYS2 (64-bit) on Windows 8.1.

**Comment by justinethier** [comment]
@kyoto-shift - Great, glad its working for you, and thanks for the feedback.

@steve4444 - Apologies this fix took so long. If you are still interested, MSYS2 support is working now on `master`.
