### ISSUE TITLE
Add SRFI 13 - String libraries

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#259]
See: https://srfi.schemers.org/srfi-13/srfi-13.html

**Comment by justinethier** [comment]
Need to see the results of the Tangerine Edition ballot before making a decision on string libraries. There is no point to adding SRFI 13 if R7RS large goes with another library.

**Comment by arthurmaciel** [comment]
If needed we could add it as a package, right? Anyway, Cyclone Winds repo already has [`SRFI-152`](https://github.com/cyclone-scheme/srfi-152) and Chibi's cursor-oriented [`string`](https://github.com/cyclone-scheme/string) library.

**Comment by justinethier** [comment]
@arthurmaciel Agreed, I will close this one.
