### ISSUE TITLE
Import statement not handled properly when there are other expressions inside a cond-expand

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#291]
The following works fine but if a (define) is added inside the cond-expand below, the program's library initializations are not performed in the proper order and the program is likely to segfault at runtime:

```
(cond-expand
  (program
    (import (scheme base)
            (scheme write)
            (scheme cyclone ast)
            (scheme cyclone primitives)
            (scheme cyclone transforms)
            (scheme cyclone cps-optimizations)
            (scheme cyclone util)
            (scheme cyclone pretty-print)
            (srfi 2)
            (srfi 69)
            )
    ))


```

**Comment by pclouds** [comment]
Perhaps related to this, this library also fails to compile because of cond-expand (verified working with chibi)

```
(define-library (abc)
  (export bar)
  (import (scheme base))

  (cond-expand
   (else
    (begin
      (define (foo) "fooz"))))

  (begin
    (define (bar) (foo))))
```

cyclone reports

```
$ cyclone -I . abc.sld 
Error: Unbound variable(s): (foo) 
Call history:
scheme/cyclone/transforms.sld:remove
scheme/cyclone/transforms.sld:difference
scheme/cyclone/transforms.sld:remove
scheme/cyclone/transforms.sld:difference
scheme/cyclone/transforms.sld:remove
scheme/cyclone/transforms.sld:difference
scheme/base.sld:list
scheme/base.sld:error
scheme/base.sld:raise
```

**Comment by justinethier** [comment]
@pclouds Re-tested and verified that the library example works now on the latest version of Cyclone. This issue was fixed along with the most recent fixes to `cond-expand` over the past few months.

Regarding the initial issue, this seems to have been fixed as well. The program, in various configurations, no longer breaks when a `define` is added. Based on these results I am closing the issue.
