### ISSUE TITLE
icyc crashes with srfi 132 list-sort

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#297]
Hi Justin! I won't time to delve into this, but I'm creating this ticket so we can sort it out in the near future:

cyclone> (import (srfi 132))
cyclone> (define l '(3 2 1))
ok
cyclone> l
(3 2 1)
cyclone> (list-sort l '())
()    **<---- I'm not sure we shouldn't have produced an error**
cyclone> (list-sort '() l )   **<--- Passing the empty list in place of a comparison operator should not segfault right?**
rlwrap: warning: icyc killed by SIGSEGV.
rlwrap has not crashed, but for transparency,
it will now kill itself (without dumping core)with the same signal

[1]    29447 segmentation fault  rlwrap icyc

**Comment by justinethier** [comment]
Hey Arthur, thanks for the report! I agree, it looks like the library should have thrown an error here because a list was passed instead of a comparison function. Let me look into it...

**Comment by justinethier** [comment]
OK, this has been fixed and merged back into `master`. Apologies for the delay...
