### ISSUE TITLE
Broken link to CheneyMTA.pdf

### ISSUE THREAD

**Issue by jpellegrini** [justinethier/cyclone#309]
Thank you for adding documentation on the internals of the system!
I have noticed that such documentation, in the file  `Writing-the-Cyclone-Scheme-Compiler-Revised-2017.md`, links to `http://www.pipeline.com/~hbaker1/CheneyMTA.html`, but unfortunately the link is broken.

**Comment by justinethier** [comment]
@jpellegrini - No problem, just updated the links with a local copy of the paper.
