### ISSUE TITLE
Investigate concurrency based on Clojure's model

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#315]
EG: https://purelyfunctional.tv/guide/clojure-concurrency/

Consider what it would take to implement Atom.

**Comment by justinethier** [comment]
Something simple like Promise might be a good place to start.

We will also need a lightweight way to guarantee:

- The concurrency object can be shared across threads. Do we need to allocate them on the heap like mutexes, etc?
- The results can be shared across threads. A minor GC will guarantee this, and is not super expensive, but it would be best if it was called as a last resort. If the data type is atomic it would be best if it could be moved directly.
- We need a new library to host all this - `(scheme cyclone concurrency)`??

**Comment by justinethier** [comment]
See also: http://wiki.jvmlangsummit.com/pdf/27_Hickey_clojure.pdf

In particular, Clojure's method is indirect references to persistent immutable data structures, as inspired by SML.

**Comment by arthurmaciel** [comment]
@justinethier, I think this is solved by [`(cyclone concurrent)`](http://justinethier.github.io/cyclone/docs/api/cyclone/concurrent), right?

**Comment by justinethier** [comment]
@arthurmaciel Agreed, closing.
