### ISSUE TITLE
Building with command line version of XCode

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#325]
Currently trying to install cyclone from its Homebrew tap says:

```
==> Installing cyclone from cyclone-scheme/cyclone
cyclone: A full installation of Xcode.app is required to compile
this software. Installing just the Command Line Tools is not sufficient.
```

How big a job would it be to make it build using just the command line tools? Some people have reservations about developer tools that require an Apple ID to download. I respect that if it's a lot of extra work for you, you want to concentrate on more productive issues.

**Comment by justinethier** [comment]
@lassik - Good question, unfortunately I do not have a Mac environment handy to test with. However, our CI script includes builds for Linux (GCC and Clang) as well as Mac (with xcode, though): https://github.com/justinethier/cyclone/blob/master/.travis.yml

If the build works with Clang on Linux then it should be possible to build with it on Mac.

**Comment by justinethier** [comment]
For what its worth this Github Action CI script works without explicitly installing Xcode:

https://github.com/justinethier/cyclone-bootstrap/blob/master/.github/workflows/ci-macos.yml

Do you have any luck running the same commands with a fresh checkout of cyclone-bootstrap?

**Comment by lassik** [comment]
Running `make` I get this:

```
cc  -O2 -fPIC -Wall -Iinclude   -c -o libs/cyclone/concurrent.o libs/cyclone/concurrent.c
libs/cyclone/concurrent.c:310:10: fatal error: 'ck_pr.h' file not found
#include <ck_pr.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by lassik** [comment]
After `brew install concurrencykit libtommath` it works fine! `make test` passes all tests, and `cyclone` can compile and link a working hello-world executable using clang.

I get some clang warnings like this:

```
srfi/133.c:1616:342: warning: shifting a negative signed value is undefined [-Wshift-negative-value]

srfi/143.c:2326:35: warning: shifting a negative signed value is undefined [-Wshift-negative-value]

unit-tests.c:1084:57: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
```

**Comment by justinethier** [comment]
@lassik This is great news, glad everything is working well for you!The build parameters have been tweaked a bit on `master` so you should no longer be spammed with these warnings.

**Comment by lassik** [comment]
Great. It's probably safe to update Cyclone's Homebrew recipe not to require full XCode as well.

**Comment by justinethier** [comment]
Agreed, xcode has been removed from the Homebrew formula.
