### ISSUE TITLE
Binary files missing

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#337]
The following routines from `(scheme file)` seem to be missing:

* `open-binary-input-file`
* `open-binary-output-file`

`(read-u8 (open-input-file "/bin/ls"))` works, but the separate binary port procedures are needed for R7RS compliance. Do you have a plan for how to implement them? I guess `(define open-binary-input-file open-input-file)` would work as a quick fix.

**Comment by justinethier** [comment]
Thanks for the report @lassik 

This appears to be a simple fix that should have been made a long time ago. Fixed in `master`.

**Comment by justinethier** [comment]
Also, note this is only really applicable for non-POSIX systems (Windows?):

       The mode string can also include the letter 'b' either as a last
       character or as a character between the characters in any of the two-
       character strings described above.  This is strictly for
       compatibility with C89 and has no effect; the 'b' is ignored on all
       POSIX conforming systems, including Linux.  (Other systems may treat
       text files and binary files differently, and adding the 'b' may be a
       good idea if you do I/O to a binary file and expect that your program
       may be ported to non-UNIX environments.)

From http://man7.org/linux/man-pages/man3/fdopen.3.html

**Comment by lassik** [comment]
Thanks for the quick response :) There are two reasons textual ports are different from binary ports:

* Textual ports use a particular character encoding, and return character objects instead of integers (`read-char` instead of `read-u8`). In principle, one could have a port where one alternates between using `read-char` and `read-byte`, but since the Scheme implementation of the port can do its own buffering and other bookkeeping, using `read-byte` on a textual port might mess up the internal state of the character reader.
* Windows uses "\r\n" (CR-LF) newlines, whereas Unix uses "\n" (LF) newlines. Lots of languages do transparent newline conversion for their textual ports, so `(newline)` writes a "\n" on Unix but a "\r\n" on Windows. Likewise when reading characters from an input port.

**Comment by lassik** [comment]
As a curiosity, some old computers (MacOS classic, some home computers and Lisp machines) used "\r" (CR only) newlines. But nowadays "\r" newlines are only of concern to hobbyists who deal with those computers.

If you call the C stdio library with "r" it does the transparent newline conversion for you. "rb" to disable that magic.
