### ISSUE TITLE
Issue with make-string and UTF-8

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#339]
Cyclone 0.11.3:

```
cyclone> (integer->char 128)
#\
cyclone> (make-string 1 (integer->char 128))
""
cyclone> (string-length (make-string 1 (integer->char 128)))
1
cyclone> (bytevector-length (string->utf8 (make-string 1 (integer->char 128))))
0
cyclone> (string-ref (make-string 1 (integer->char 128)) 0)
Error: string-ref - invalid character at index: 0
```

**Comment by justinethier** [comment]
Thanks for the bug report @lassik ! 

This has been fixed on `master` and will be included in the next release.

**Comment by lassik** [comment]
Great, thanks for the quick response :) If you feel like it, please ping us at [weinholt/scheme-docker](https://github.com/weinholt/scheme-docker) when it's ready and we'll update the Docker container.
