### ISSUE TITLE
read-u8 can return characters instead of integers

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#340]
All of the SRFI 175 examples work with Cyclone 0.11.4, except one. The bug is here:

```
$ cat test.scm
(import (scheme base) (scheme file) (scheme read) (scheme write))
(call-with-port (open-binary-input-file "test.scm")
                (lambda (in) (write (read-u8 in)) (newline)))
$ cyclone test.scm
$ ./test
#\(
```

**Comment by justinethier** [comment]
Good catch @lassik ! This was a bad oversight on my part and has been corrected for each of the byte-oriented I/O functions.

**Comment by lassik** [comment]
Wow, fast work! Thank you very much.

**Comment by lassik** [comment]
Let me know when the next release is out. I'll update the Dockerfile and add Cyclone to the list of tested implementations in SRFI 175.
