### ISSUE TITLE
What architectures and platforms do Cyclone support?

### ISSUE THREAD

**Issue by s14k51** [justinethier/cyclone#342]

**Comment by justinethier** [comment]
Linux, Windows, FreeBSD, and Mac platforms. To my knowledge it runs on x86-64, x86, and Arm (Raspberry Pi).

Do you have a specific system in mind?

**Comment by s14k51** [comment]
I was looking for ARM support. Thanks.

**Comment by justinethier** [comment]
No problem, would be curious how it works out :)

**Comment by s14k51** [comment]
Sure, I'm planning to run it on a raspberry pi, but I don't have an estimate of when I would actually do that. He he. Cheers.
