### ISSUE TITLE
Implement bytevector I/O

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#350]
How much work would it be to implement `read-bytevector`, `read-bytevector!` and `write-bytevector`?

**Comment by justinethier** [comment]
Good question. Now that we have the corresponding `u8` functions in place, I think these could be implemented in a straightforward manner as wrappers on top of those functions.

**Comment by lassik** [comment]
You're using C stdio, right? For big buffers it's probably faster to use `fread()` and `fwrite()`. I stdio does its own buffering anyway.

**Comment by justinethier** [comment]
Agreed, all of our reads are done by using `fread` to read in bulk and then read operations are performed against our in-memory buffer. I can certainly look into using `fwrite`, that's a good idea.

In either case I think we are still good adding the functions you requested by building them on top of the lower-level constructs already in place.

**Comment by lassik** [comment]
That can certainly be done, but this would be a great time to implement real bulk I/O :)

fwrite() just takes a `void *` buffer and a `size_t` size, just like Unix `read()`. If you have your own buffering, you probably have the right stuff already.

**Comment by lassik** [comment]
The main tricky situation is what happens when the caller wants to read more data than Cyclone's internal per-port buffer holds. Then one `read-bytevector` needs to do multiple reads and concatenate the results.

**Comment by justinethier** [comment]
Right, but that is already handled today. If there is no more data in the internal buffer then our runtime calls `fread` to fill it back up.

**Comment by justinethier** [comment]
That doesn't sound too bad with `fwrite`. If we know we are going to be doing a bulk write then we can just call into that directly.

**Comment by lassik** [comment]
> Right, but that is already handled today. If there is no more data in the internal buffer then our runtime calls `fread` to fill it back up.

Cool! So the hard parts are done.

`fread()` is also almost identical to Unix `read()`. Whereas Unix read and write take a single size argument, fread and fwrite take size and count arguments like `calloc()` does. But you can just pass 1 for the count and they work the same as the Unix syscalls.

**Comment by lassik** [comment]
Oops, you probably knew that already :)

**Comment by justinethier** [comment]
No problem :)

These functions have all been added on `master` and will be in the next release.

**Comment by lassik** [comment]
Thanks a lot :)
