### ISSUE TITLE
clang spams a lot of warnings about unused command line arguments when compiling cyclone

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#351]
Clang profusely complains about unused command line argumets when compiling cyclone. 

Example (happens for every compiled lib):
cyclone -A . libs/cyclone/match.sld
cc: warning: -Wl,--export-dynamic: 'linker' input unused [-Wunused-command-line-argument]
cc: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]

As the -Wno-shift-negative-value flag was added to compiler flags, I think -Wno-unused-command-line-argument should be too.

**Comment by justinethier** [comment]
Agreed. This has been fixed in `master`.

**Comment by arthurmaciel** [comment]
It also happens with other flags when compiling with cyclone-winds, as is the cas of -Wshift-negative-value:

test.c:35036:39: warning: shifting a negative signed value is undefined [-Wshift-negative-value]
  return_closcall1(data,  k_7363509,  obj_int2obj(-10));; 
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
/usr/local/include/cyclone/types.h:609:44: note: expanded from macro 'obj_int2obj'
#define obj_int2obj(c) ((void *)((((long)c)<<1) | 1))
                                           ^
test.c:23:36: note: expanded from macro 'return_closcall1'
     closcall1(td, (closure) (clo),a1); \
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
test.c:14:27: note: expanded from macro 'closcall1'
   ((clo)->fn)(td, 1, clo,a1);\
                          ^~

**Comment by justinethier** [comment]
@arthurmaciel - What platform are you building on?

**Comment by arthurmaciel** [comment]
The same for:

test.c:3796:3: warning: expression result unused [-Wunused-value]
  boolean_f;return_closcall1(data,  k_734108,  quote_ok);;; 
  ^~~~~~~~~

**Comment by arthurmaciel** [comment]
Justin, I'm on x64 FreeBSD 12.1 clang 8.0.1.

Em qui, 27 de fev de 2020 16:07, Justin Ethier <notifications@github.com>
escreveu:

**Comment by arthurmaciel** [comment]
Same for: -Wunused-command-line-argument

cc: warning: argument unused during compilation: '-L/usr/local/lib' [-Wunused-command-line-argument]

**Comment by justinethier** [comment]
@arthurmaciel When you have a chance please try again using a copy of cyclone build against the latest `master`.

**Comment by arthurmaciel** [comment]
@justinethier , except for the following warning, all of them were silenced! Thanks!

./test.c:27379:3: warning: expression result unused [-Wunused-value]
  boolean_f;return_closcall1(data,  k_73114067,  quote_ok);;; 
  ^~~~~~~~~

**Comment by justinethier** [comment]
@arthurmaciel Which file/project were you compiling to get the above warning? I do not see it when building cyclone and cyclone-winds on a FreeBSD 12 VM...

**Comment by arthurmaciel** [comment]
@justinethier, I'm so sorry, but I can't recall at the moment.

**Comment by arthurmaciel** [comment]
The following happens when running `$ sudo ./install.sh` on `cyclone-bootstrap`, but I am pasting here because maybe it could be is useful for tracking all warnings emitted by `clang` on `FreeBSD 12.1`:

```
  -DCYC_CC_PROG=\""cc ~src-file~  -O2 -Wall -I/usr/local/include -c -o ~exec-file~.o"\" \
  -DCYC_CC_EXEC=\""cc ~exec-file~.o ~obj-files~ -pthread -lcyclone -lck -lm -lcyclonebn  -O2 -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument -I/usr/local/include -L/usr/local/lib -Wl,--export-dynamic -o ~exec-file~"\" \
  -DCYC_CC_LIB=\""cc ~src-file~  -O2 -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument -I/usr/local/include -L/usr/local/lib -Wl,--export-dynamic -c -o ~exec-file~.o"\" \
  -DCYC_CC_SO=\""cc -shared -L.  -Wl,--export-dynamic -L/usr/local/lib -o ~exec-file~.so ~exec-file~.o"\" \
  -DCYC_PLATFORM=\"bsd\" \
  runtime.c -o runtime.o
runtime.c:7608:46: warning: result of comparison of constant -1
      with expression of type 'uint8_t' (aka 'unsigned char')
      is always true
      [-Wtautological-constant-out-of-range-compare]
    return_thread_runnable_with_obj(data, (c != EOF) ? ...
                                           ~ ^  ~~~
```

**Comment by arthurmaciel** [comment]
For the record:

```
$ sudo cyclone-winds install packrat  
Retrieving index file...
Downloading packrat (version 0.1)...
Building and installing packrat...
./packrat125463531/cyclone/packrat.c:15522:39: warning: trigraph ignored
      [-Wtrigraphs]
make_utf8_string_with_len(c_733221, "<??>", 4, 4);
                                      ^
1 warning generated.
Package packrat (version 0.1) successfuly installed with Cyclone 0.19.
```

**Comment by justinethier** [comment]
Both of the last two warnings have been fixed on the `master` branch.
