### ISSUE TITLE
Batch compiler

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#354]
It would be so much friendlier if there was a batch compiler that would take EG `compile program.scm` and build all the associated libraries automatically as well as creating a final executable. 

It is asking a lot to have someone write makefiles just to use libraries.

**Comment by justinethier** [comment]
EG: `csc` vs `chicken`

**Comment by amirouche** [comment]
What about the following:

```
cyclone --program program.scm
```

Will compile everything and run.

**Comment by amirouche** [comment]
Nevermind, batch compiling is good enough.

**Comment by justinethier** [comment]
@amirouche I was thinking of having a way to drive multiple calls to the compiler, one for each dependent library to be compiled. 

For example, chicken has separate commands for this:
http://wiki.call-cc.org/man/5/Using%20the%20compiler

I suppose our front-end could use separate commands or possibly it could all be done using `cyclone` with command-line options (maybe run as the driver by default?). The front end portion is TBD; regardless of the interface code still needs to be written to collect dependencies, verify timestamps, build each library, etc.

**Comment by justinethier** [comment]
OK, so the way this works now is:

- When compiling a program with `cyclone` any library dependencies will be automatically built as well.
- A library will only be built if an object file does not exist for it or the `.sld` source file is newer than the object file.
- Only "local" libraries will be built. Cyclone will not automatically attempt to build libraries in system directories.
- This capability can be disabled by the `-no-batch` option.

**Comment by amirouche** [comment]
Thanks for the quick resolution.  I think this will greatly improve cyclone usability.

>     * A library will only be built if an object file does not exist for it or the `.sld` source file is newer than the object file.

Does it take into account what is `include` when checking if a `.sld` source file changed.

By the way, I am busy nowadays, I will not be able to test it right away.

**Comment by justinethier** [comment]
You're welcome @amirouche . This capability was long overdue.

`include` directives are not taken into account right now, but they should be. Let me see what can be done.

No worries on testing. Thanks for your help on this issue, and any additional feedback or input is always appreciated.

**Comment by justinethier** [comment]
We will probably need an equivalent (or similar) function to `lib:read-imports` that reads all the includes from a library. Then we can check those includes when determining if a library needs to be recompiled.

**Comment by justinethier** [comment]
OK, the logic now takes `include` into account. Closing...
