### ISSUE TITLE
Game of life example does not work with icyc

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#355]
I think this is due to some of the import directives not being handled properly by the interpreter.

**Comment by arthurmaciel** [comment]
I am not sure this is related but I don't think the following behavior is expected:

```
cyclone> (define a 1)
ok
cyclone> (import (scheme write))
ok
cyclone> a
Error: Unbound variable: a 
```
It doesn't matter here which library is imported, as long as the `import` itself succeeds:

```
cyclone> (define a 1)
ok
cyclone> (import (b c))
Error: Unable to open file: ".//b/c.sld" 
cyclone> a
1
```

**Comment by justinethier** [comment]
The problem is that an import re-initializes the global environment, which overwrites any existing data in the environment. This behavior is unfortunate... we need to figure out an alternative solution.

**Comment by justinethier** [comment]
Modified the global environment to use a dedicated "area" for everything above the compiled primitives. That way, when we re-load the global environment after an import, we can just re-insert this area after re-loading a new set of primitives.

Still need to address issues with renaming. Should be a matter of making `%import` in the `eval` module aware of the renaming done by the import sets.

**Comment by justinethier** [comment]
The REPL should now behave as expected, EG:

```
cyclone> (define a 1)
ok
cyclone> (import (scheme write))
ok
cyclone> a
1
```

**Comment by justinethier** [comment]
Game of life now works directly in `icyc`.
