### ISSUE TITLE
Division does not always coerce to an inexact value when the result is not exact

### ISSUE THREAD

**Issue by yorickhardy** [justinethier/cyclone#357]
The second paragraph on page 33 of R7RS says that (/ 3 4) should not return 0.
The following program works correctly when interpreted by icyc, but returns 0 for (/ a b) when compiled by cyclone (tested on NetBSD using the cyclone bootstrap).

(import (scheme base) (scheme write))

(define a 3)
(define b 4)
(display (/ a b))
(newline)
(display (/ 3 4))
(newline)

**Comment by justinethier** [comment]
OK, this has been fixed in `master`. I am curious where you see this mentioned in R7RS...

**Comment by yorickhardy** [comment]
Great! Thank you.

I don't see an easy way to quote R7Rs, so Section 6.2.2 page 33 second paragraph (second last sentence, emphasis is mine):

"Rational operations such as + should always produce exact results when given exact arguments. If the operation is unable to produce an exact result, then it may either report the violation of an implementation restriction or it may silently coerce its result to an inexact value. _However,  (/ 3 4) must not return the mathematically incorrect value 0._ See section 6.2.3."

and Section 6.2.3 fifth paragraph (emphasis is mine)

"It is recommended, but not required, that implementations support exact integers and exact rationals of practically unlimited size and precision, and to implement the above procedures and the   procedure in such a way that they always return exact results when given exact arguments.  _If one  of these procedures is unable to deliver an exact result when given exact arguments, then it may either report a violation of an implementation restriction or it may silently coerce its result to an inexact number_; such a coercion can cause an error later."

**Comment by justinethier** [comment]
No problem. Apologies, I missed that the first time through but see it now. It's interesting R7RS explicitly calls out this operation but I see what they are getting at. Anyway, it is fixed on `master` and will be available in our next release. Thanks for reporting this issue :)
