### ISSUE TITLE
Support a/b syntax for numbers

### ISSUE THREAD

**Issue by yorickhardy** [justinethier/cyclone#358]
Superficial reading of page 62 of R7RS suggests that

  <ureal R>  -->  <uinteger R> / <uinteger R>

allows for fractions etc. I think that cyclone can coerce 1/2 to 0.5 for example.

Should the parser support this? (it seems it must, but perhaps I missed something!).

**Comment by justinethier** [comment]
Cyclone currently does not support rational numbers so the reader does not recognize `1/2`. The rest of the numeric tower is supported, however.

**Comment by yorickhardy** [comment]
I just noticed that the BNF rule did not display as intended.

Apologies for being a nuisance, and I may again be missing something. "1/2" currently evaluates to "#f" in icyc instead of reporting an error. Is this intentional?

The main reason for raising the issue, is that 1/2 appears to be valid syntax even if rational numbers are not supported and should yield a  "ureal 10", or (presumably) an error if real numbers are not supported.

Should 

> #i1/2

give an inexact 1/2 ?

I consulted page 62 of R7RS, the rule for "number", "num 10", "prefix 10", "exactness" and "complex 10", "real 10", "ureal 10" and came to the conclusion that the desired result is 0.5; and in the absence of rational numbers is seemed desirable to translate 1/2 to #i1/2 and then to 0.5.

Apologies for asking you to read through all of this!

Please feel free to close the issue if I am misreading R7Rs or if this makes no sense for cyclone.

**Comment by yorickhardy** [comment]
On reading the last paragraph of R7RS Section 6.2.3 again, I see that I am mistaken. (The full syntax for numbers does not need to be supported).

Apologies!
