### ISSUE TITLE
Add cyclone-winds binary target to bootstrap

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#364]
This binary should be released as part of `cyclone-bootstrap`.

As part of this we will probably want to tag `cyclone-winds` using the same version scheme as cyclone, just to keep everything in sync.

**Comment by justinethier** [comment]
As part of this effort documentation for cyclone-winds needs to be added to the website and README's. IE, users need to know that the package manager exists, how to get it, and where to go for more detailed information about usage.

**Comment by arthurmaciel** [comment]
@justinethier, I've seen you're already including cyclone-winds into core. I am almost finishing an improvent in docs generation, by including procedures signatures :)

I'll probably finish it tomorrow. I just need to polish the code, but it is already working. Do you think is it possible to include the newer version before 0.18 release?

Thanks!

**Comment by justinethier** [comment]
@arthurmaciel Absolutely. Just let me know when you are ready and I will pull it in.
