### ISSUE TITLE
list-copy does not return non-list object

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#367]
R7RS states:

https://small.r7rs.org/attachment/r7rs.pdf

>  An obj which is not a list is returned unchanged.

but Cyclone `list-copy` procedure rejects it.

```scheme
cyclone> (list-copy 'a)
Error: Invalid type: expected pair, found : a
```

tested: https://github.com/justinethier/cyclone/commit/fcf6b04e780a58c25676c9fb3878369004e6d721

Other Scheme does have same issue: MIT/GNU Scheme (10.x)

**Comment by justinethier** [comment]
Good catch. We can use a different version of `list-copy` that makes that guarantee.
