### ISSUE TITLE
bytevector? procedure always return #f

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#368]
R7RS `bytevector?` procedure should return `#t` for bytevectors and return `#f` otherwise.

Cyclone `bytevector?` procedure seems always return `#f` even for bytevectors.

```scheme
cyclone> (bytevector? #u8())
#f
cyclone> (bytevector? (bytevector))
#f
cyclone> (define x (bytevector))
ok
cyclone> x
#u8()
cyclone> (bytevector? x)
#f
```

... Since displaying bytevector object works well here, there is some chance it is my local problem. Let me know in case you cannot reproduce this.

tested: https://github.com/justinethier/cyclone/commit/fcf6b04e780a58c25676c9fb3878369004e6d721

**Comment by justinethier** [comment]
Good catch, there was a typo which was causing the code for `vector?` to be called instead! This has been fixed on `master` and will be in the next release.
