### ISSUE TITLE
String comparision procedures ignores 3rd or beyond arguments

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#369]
R7RS string comparison procedures should always process every specified arguments but it seems it does not work as intended on Cyclone.

```scheme
cyclone> (string<? "1" "2" "0")
#t
cyclone> (string<? "1" "2" 'wrong)
#t
```

Affected procedures are: `string=?` `string<?` `string<=?` `string>?` and `string>=?`

Number and symbol comparison procedures are not affected.

```scheme
cyclone> (< 1 2 0)
#f
cyclone> (< 1 2 'wrong)
Error: Invalid type: expected number, found : wrong
```

tested: https://github.com/justinethier/cyclone/commit/fcf6b04e780a58c25676c9fb3878369004e6d721

**Comment by justinethier** [comment]
Good catch. Yes, I am aware of this issue. Let me investigate what it will take to generalize these procedures. This may be a bit of a slower turnaround though :)

**Comment by justinethier** [comment]
Fixed and will be included in the next release. Thanks for the bug report @okuoku !
