### ISSUE TITLE
(cyclone foreign) library

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#370]
This ticket tracks the progress of the `(cyclone foreign)` library.

**Comment by justinethier** [comment]
Work is coming together, need to address TODO item in the library and add remaining types from `scm->c`.

May also consider adding more forms to the library.

**Comment by arthurmaciel** [comment]
I let this reference here just for the record (just stumbled across it): http://synthcode.com/scheme/chibi#h2_CFFI

**Comment by arthurmaciel** [comment]
@justinethier, I realized `(cyclone foreign)` handles bignums on `scm->c`, but not on `c->scm`:

```
c->scm unable to convert C object of type : 
bignum
```
I couldn't find something like `make_bignum` in the C API to try to implement this by myself. Could you point please the way to go? Thanks!

**Comment by justinethier** [comment]
@arthurmaciel Good catch! Yes, you want to use [`alloc_bignum`](https://github.com/justinethier/cyclone/blob/master/include/cyclone/types.h#L830) to create the bignum object. Unfortunately these cannot be allocated on the stack which is why there is no `make_` function.

Here is how to initialize a bignum from a string value:

    alloc_bignum(data, c_7310); 
    BIGNUM_CALL(mp_read_radix(&bignum_value(c_7310), "11111111111111111111111111", 10));

That would be a straightforward way to receive a bignum.

**Comment by arthurmaciel** [comment]
Thanks, @justinethier. But I am not sure it would be the most common scenario for a C function to return a bignum as a string. Don't you think anyone hacking with C to speed-up code would use `mp_int` or `mp_int *` as return values and/or arguments types?

If so, is it ok to do the following?

```C 
alloc_bignum(data, c_7310); 
c_7310->bn = variable_of_mp_int_type; 
```

An extended example:

```C
// Some custom function to speed-up code
mp_int sub_big_nums(mp_int bnx, mp_int bny) {
    alloc_bignum(data, bn);
    BIGNUM_CALL(mp_sub(&bnx, &bny, &bignum_value(bn)));

    return bignum_value(bn);
}
```

In Scheme:

```Scheme
(c-define sub-big-nums bignum "sub_big_nums" bignum bignum)
```

On `c->scm` in foreign:
```
;; c->scm on case:
((bignum)
  (let ((var (mangle (gensym 'var))))
    (cons
     (string-append 
      "alloc_bignum(data," var ");"
      var "->bn = " code ";")
     (string-append "&" var))))
``` 

What do you think of the above code? Thanks!

**Comment by justinethier** [comment]
@arthurmaciel I like where you are going with this. The main problem is how to pass the thread data object to the foreign function. The above commit adds `data` support as a hack but that really doesn't work because `data` is not exposed at the scheme layer. It would probably be better to pass a parameter that tells foreign to include the data parameter in the call. Anyway, need to spend more time wrapping up that detail.

**Comment by arthurmaciel** [comment]
Oh, what a shame, Justin! Sorry for that. I didn't noticed that (big)
detail.

Em sáb, 23 de jan de 2021 02:10, Justin Ethier <notifications@github.com>
escreveu:

**Comment by justinethier** [comment]
No worries @arthurmaciel this is an important use case that the foreign library never addressed. Lets give it some thought and see if there is a good solution.

**Comment by arthurmaciel** [comment]
@justinethier, thanks!

Just as a side notes (and probably new issues):
- on `scm->c` it would be quite helpful to insert type checks with `Cyc_check_...` for each data structure. Many segfaults I am facing with the Scheme<->Python integration are due to wrong parameters types. I a mentioning this because `Cyc_check_...` depends on `data` too.

- I know we can use `vector->list`, but would it be useful to support Scheme `vectors` directly?

**Comment by justinethier** [comment]
OK, here is an initial solution, certainly open to further suggestions:

Added (current-thread-data) to (srfi 18) to get the data object. Here is a full example plugging everything together:

`test-bn.h`:

```
#include "cyclone/types.h"

// Some custom function to speed-up code
mp_int sub_big_nums(void *data, mp_int bnx, mp_int bny) {
    alloc_bignum(data, bn);
    BIGNUM_CALL(mp_sub(&bnx, &bny, &bignum_value(bn)));

    return bignum_value(bn);
}
```

```
(import (scheme base) (scheme write) (cyclone foreign) (srfi 18))
(include-c-header "test-bn.h")

(c-define sub-big-nums bignum "sub_big_nums" opaque bignum bignum)

(write
  (sub-big-nums
     (current-thread-data)
     999999999999999999999999
     222222222222222222222222
     ))

```

```
$ ./test-bn
777777777777777777777777
```

**Comment by justinethier** [comment]
Will need to document the above, and perhaps include an example, so users know what to do :)

**Comment by arthurmaciel** [comment]
@justinethier, how nice!! Thanks for that!

Do you think we could automate the process of passing `(current-thread-data)` in procedure call and the `opaque` in procedure definition, by hiding the to the user, with a macro?

**Comment by arthurmaciel** [comment]
@justinethier, sorry - I shared only half of my thoughts: in order to have type checks using `Cyc_check_...` for every data type, we would need the `data` variable anyway, so every FFI procedure would need to call with `(current-thread-data)`. I will try to think of a solution. If you have one, but would not have time to implement it, please let me know. 

> @justinethier, how nice!! Thanks for that!
> 
> Do you think we could automate the process of passing `(current-thread-data)` in procedure call and the `opaque` in procedure definition, by hiding the to the user, with a macro?

**Comment by justinethier** [comment]
@arthurmaciel I think we will want to have either an alternate version of `c-define` or an optional argument to the macro that will generate a function call that passes `data` to the C function without needing for it to be an explicit argument. As part of this we can also emit type checks.

Open to suggestions on how to do this. Perhaps `c-define-safe`? Taking it a step further we could have 3 forms:

- `c-define-safe` - Same macro as above
- `c-define-unsafe` - Same as what we have today
- `c-define` - We can change this to be the same as `c-define-safe` so generated code is safe by default.

Thoughts?

**Comment by arthurmaciel** [comment]
@justinethier, don't `define-c` and even `c-code` perform (or allow the performance of) the functionality that would be provided by `c-define-unsafe`?

**Comment by justinethier** [comment]
@arthurmaciel That's a good point. Taking a step back there are 2 separate concerns:

1. Performing type checks on parameters prior to handing those parameters off to a C function
2. Passing the current `gc_thread_data` to a C function

Agreed the high level interface can - and should - always perform (1). In the rare case there is a performance issue or other concern the user can drop back to using the lower-level interfaces.

I would like to make (2) explicit in the `c-define` in order to allow integrating with functions that may not accept a `gc_thread_data` argument (for example: `strlen`). Perhaps the best way to do this is to have a dedicated type specifier `thread-data` or such that is just a passthrough for the C `data` argument. That way we can keep everything within `(cyclone foreign)`. This also avoids the current dependency on `(srfi 18)` / `opaque` which I agree is a poor long-term solution.

**Comment by arthurmaciel** [comment]
@justinethier, this idea sounds great! It is succinct and clear to the user. Thanks for that!

**Comment by justinethier** [comment]
@arthurmaciel No problem, this discussion was very helpful, thanks!

The type checking is in place now on the `master` branch. Please try it out when you have a chance and let me know how it goes :) 

Still need to figure out the details for passing the thread data object but planning on working that next.

**Comment by justinethier** [comment]
Added the `thread-data` type specifier.

@arthurmaciel Please see the above commit for an example of how to use `thread-data`. This should be much cleaner than before :)

**Comment by arthurmaciel** [comment]
@justinethier, that is awesome! Thanks for that!

**Comment by arthurmaciel** [comment]
@justinethier, testing `(cyclone foreign)` a bit with the `(cyclone python-foreign)` (alpha version to be release soon) the linker complains about a missing reference to `Cyc_check_double`. In Cyclone source code I couldn't find it nor a related `Cyc_is_double`, common to other `Cyc_check_...` functions. As it is a bit deep into Cyclone internals, would you mind to assign this issue to you?

**Comment by justinethier** [comment]
@arthurmaciel No trouble, I thought I included those functions with this round of changes. They are there now on the `master` branch.

**Comment by justinethier** [comment]
This library has been available for some time now. Closing...
