### ISSUE TITLE
Maybe compilation error in some cases of "apply" usage

### ISSUE THREAD

**Issue by marcomaggi** [justinethier/cyclone#371]
I have started porting a bit of code to Cyclone Scheme, on my Slackware64 14.2, `x86_64-pc-linux-gnu`, GCC 10.1.0, using Cyclone bootstrap 0.17.  Everything is new for me with Cyclone, so I am just starting to look around in the programming environment.

The code is in [this](https://github.com/marcomaggi/mmux-cyclone-scmobj) repository.  When I run the compilation, I get the error:

```
/home/marco/bin/cyclone -I ./build-lib -I ../lib  build-lib/mmux.cyclone.scmobj.sld
Error: unknown exp: : ()
Call history:
scheme/cyclone/util.sld:define-syntax?
scheme/cyclone/util.sld:tagged-list?
scheme/cyclone/util.sld:let-syntax?
scheme/cyclone/util.sld:tagged-list?
scheme/cyclone/util.sld:letrec-syntax?
scheme/cyclone/util.sld:tagged-list?
scheme/cyclone/util.sld:app?
scheme/base.sld:error
scheme/base.sld:raise

Makefile:1438: recipe for target 'build-lib/mmux.cyclone.scmobj.so' failed
make: *** [build-lib/mmux.cyclone.scmobj.so] Error 1
```

It seems to be caused by forms in which `apply` is applied to a first operand which is an expression, rather than a variable reference.  Specifically in the file `lib/mmux.cyclone.scmobj.sld`, around [line 614](https://github.com/marcomaggi/mmux-cyclone-scmobj/blob/3c6cdfc10b8259ef0ac4a905cf8a587679cae6d1/lib/mmux.cyclone.scmobj.sld#L614), the `cond` form makes repeated use of the syntax `apply-function/stx` and its expansion is the one that causes the error.  If I comment out the `cond` form (as in `#f #;(cond`) libraries compilation completes successfully.

I was not able to isolate a small chunk of code that causes this.  I do not even understand if the error is at expand-time or compile-time, or both.

Thanks in advance.

**Comment by justinethier** [comment]
How can I reproduce this using a fresh clone of your repo? For example I do not see a `build-lib`.

**Comment by marcomaggi** [comment]
On a GNU+Linux system with the GNU Autotools installed, you can run this script in a temporary directory (it will execute the procedure explained in the `README` file):

```
#!/bin/bash
#
# Cyclone Scheme: hurt me with issue 371.

set -ex
git clone --depth=1 https://github.com/marcomaggi/mmux-cyclone-scmobj
cd mmux-cyclone-scmobj
./autogen.sh
./configure --enable-maintainer-mode
make

### end of file
```

Sorry for this trouble, but since I was not able to isolate the cause of the error, I was not able to produce a small source file that replicates it.

**Comment by justinethier** [comment]
Errors out with the following:

    configure.ac:32: error: require Automake 1.16, but have 1.15

Is automake 1.16 really required?

**Comment by marcomaggi** [comment]
I do not remember: I always use the latest to get all the bug fixes; and I just require the latest because it is easier.  You can install it in 1 minute:

```
#!/bin/sh

set -ex
wget http://ftp.gnu.org/gnu/automake/automake-1.16.tar.gz
tar xvzf automake-1.16.tar.gz
cd automake-1.16
./configure --prefix=/usr/local --prefix=/usr/local/lib64
make
(umask 0; sudo make install)

### end of file
```

**Comment by justinethier** [comment]
Looks like there is a problem expanding the `begin0` macro which is used by the `consume-closure` macro as well as being used directly in this section of code.

Are you able to recreate a smaller use case?

**Comment by marcomaggi** [comment]
Fixed thanks.  There were some typos in `lambda`.  Sorry for this noise.  Is there a way to get a line number of the failing expression?
