### ISSUE TITLE
Which library files do need to be installed?

### ISSUE THREAD

**Issue by marcomaggi** [justinethier/cyclone#372]
Scenario: package A compiles some libraries and installs them; package B needs libraries from A to compile its own libraries and programs.  Which library files does package A need to install?

It seems that installing the `.so` files is not enough.  Should I install the `.sld` files too (this I would not understand)?  Should I install the `.meta` files (this I would understand)?

I get errors about missing `.sld` files even when I add the `-I` option to select the location of the source files.

Is this specifically documented somewhere?

**Comment by justinethier** [comment]
Good question @marcomaggi . The documentation has been updated to include this information: http://justinethier.github.io/cyclone/docs/User-Manual#generated-files

And yes, the `.sld` files are required to be installed.

**Comment by marcomaggi** [comment]
The object files `.o` also need to be installed?  And they must all go under the same
directory?    Is there some constraint like: the `.so` file must have modification time
newer than the `.sld` file (some Scheme implementations have something like that)?

I guess  the `.so`  files are needed  when running an  executable program;  the other
files are  needed only when compiling  new binaries.  Can  I put the `.so`  under one
directory (example: `/usr/local/lib64/`); and the other files under another directory
(example: `/usr/local/lib64/cyclone/`)?    Then just give the correct `-I` options?

You are not leveraging the full power of  compiling to the C language.  I really wish
Cyclone could  be use to transform  Scheme to C and  then I could write  the rules to
compile to binaries myself, with all the possibilities of the C language:

* Linking multiple `.o` files into a  single executable, or shared library, or static
library.

* Using GNU Libtool to build shared and static libraries.

* Maybe for shared libraries: install only two  `.so` files, one for run-time and one
for expand-time  holding the compiled  macros exported  by the library  (and whatever
else is needed).

Would  this be  too  much work?   IMHO  it  would make  Cyclone  somewhat unique  and
featureful: I do not recall any other Lisp implementation that allows this.

**Comment by marcomaggi** [comment]
While we are at it: when I install a new Cyclone revision, should the binaries (especially the shared libraries) be recompiled or do they work with any Cyclone revision, unless otherwise stated?

**Comment by justinethier** [comment]
Perhaps this needs to be better documented, but when you use the `-d` flag to only generate `.c` files the compiler also emits the commands it would have used to generate native code:

```
[justin@justin-pc cyclone]$ cyclone -d icyc.scm
cc icyc.c  -O2 -Wall -I/usr/local/include -c -o icyc.o
cc icyc.o  /usr/local/share/cyclone/scheme/cyclone/common.o  /usr/local/share/cyclone/scheme/base.o  /usr/local/share/cyclone/scheme/time.o  /usr/local/share/cyclone/scheme/inexact.o  /usr/local/share/cyclone/scheme/char.o  /usr/local/share/cyclone/scheme/cyclone/util.o  /usr/local/share/cyclone/scheme/read.o  /usr/local/share/cyclone/scheme/process-context.o  /usr/local/share/cyclone/scheme/cyclone/libraries.o  /usr/local/share/cyclone/scheme/write.o  /usr/local/share/cyclone/scheme/cyclone/hashset.o  /usr/local/share/cyclone/srfi/69.o  /usr/local/share/cyclone/scheme/cyclone/primitives.o  /usr/local/share/cyclone/scheme/file.o  /usr/local/share/cyclone/scheme/eval.o  /usr/local/share/cyclone/scheme/repl.o  /usr/local/share/cyclone/scheme/load.o  /usr/local/share/cyclone/scheme/lazy.o  /usr/local/share/cyclone/scheme/cyclone/pretty-print.o  -pthread -lcyclone -lck -lm -lcyclonebn -ldl  -O2 -fPIC -Wall -Wno-shift-negative-value -Wno-unused-command-line-argument -I/usr/local/include -L/usr/local/lib -Wl,--export-dynamic -o icyc
```
At that point you can plug all of this into whatever build system you want.

The reason all of the other files are required is due to how Cyclone's compiler handles builds internally. It does need `.sld` and `.meta` files to handle compilation to C but the rest of the files are not required if you wanted to use your own build system.

Does that help?

Most likely the files would need to be recompiled when a new release is made. If you package everything up using [our package manager](https://github.com/cyclone-scheme/cyclone-winds) it will handle that automatically on upgrade. Though that would imply using Cyclone to build everything...

**Comment by marcomaggi** [comment]
All right.  I will study this solution in my projects (I am not friend with language-specific packages).

Unless I am mistaken once again: there is no mention of the package manager and the available packages on the [site](http://justinethier.github.io/cyclone/) and on the [Github home page](https://github.com/justinethier/cyclone).  This is why I have started [this Wiki page](https://github.com/justinethier/cyclone/wiki/Libraries-contributed-to-the-Cyclone-Scheme-programming-environment),  because I was not aware of [this Wiki page](https://github.com/cyclone-scheme/cyclone-winds/wiki).

I will soon transfer documentation of my projects into their own page.

**Comment by marcomaggi** [comment]
Out of topic: I gather it is also possible to build and install shared `libcyclone` libraries with `cyclone-bootstrap` rather than the default static libraries.  I wish this could be documented in the `README` files.

**Comment by justinethier** [comment]
@marcomaggi We will be releasing the package manager officially in the next 0.18 release. But it is ready to go at this time.

Right now libcyclone is only built as a static library. We would need to add another target for the shared version of the library.
