### ISSUE TITLE
Error parsing options, collect-opt-values parses only the first one

### ISSUE THREAD

**Issue by marcomaggi** [justinethier/cyclone#373]
I think there is a bug in `collect-opt-values` in the file `cyclone.scm` in commit fcf6b04e780a58c25676c9fb3878369004e6d721; the following script:

```
(import (scheme base)
	(scheme cyclone pretty-print))

(define (collect-opt-values args opt)
  (cdr
    (foldl
      (lambda (arg accum)
        (cond
          ((equal? arg opt)
           (cons opt (cdr accum)))
          ((car accum) ;; we are at an opt value
           (cons #f (cons arg (cdr accum))))
          (else
           (cons #f (cdr accum)))))
      (list #f)
      args)))

(pretty-print (collect-opt-values '("-a" "1" "2") "-a")) ;; ==> ("1")
(pretty-print (collect-opt-values '("-a" "1" -a "2" -a "3") "-a")) ;; ==> ("1" "2" "3")
```

prints:

```
("1")
("1")
```

rather than:

```
("1")
("1" "2" "3")
```

as expected.  This causes, for example, the option `-I` to be recognised only once.

**Comment by justinethier** [comment]
Good catch, let me investigate.

**Comment by arthurmaciel** [comment]
Dear @marcomaggi, there is a small error on your example:

`(collect-opt-values '("-a" "1" -a "2" -a "3") "-a"))`

You are passing a list with 6 elements, one **string** `"-a"`, `"1"`, then a **symbol** `'-a`, `"2"`, then the same **symbol**  `'-a` and finally `"3"`. As `opt` you are passing a **string** `"-a"`. So the result is as expected. 

I understand the emergence of this subtle error: the [example](https://github.com/justinethier/cyclone/blob/228f606b2e7518ad1230c71a86afd1421334f6f1/cyclone.scm#L813) on the source code is wrong too. 

Here `(pretty-print (collect-opt-values '("-a" "1" "-a" "2" "-a" "3") "-a"))` produces `("3" "2" "1")` as we are using `foldl` and not `foldr`. If you feel satisfied with this explanation, could you please close the issue? 

Cheers,
Arthur

**Comment by marcomaggi** [comment]
@arthurmaciel You are right.

**Comment by justinethier** [comment]
This is great, thanks @arthurmaciel !
The example code has been fixed to avoid confusion going forward.
