### ISSUE TITLE
Primitive open-binary-output-file and open-binary-input-file are not exported

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#374]
It seems `open-binary-output-file` and `open-binary-input-file` are not accessible from REPL. 

```
cyclone> open-binary-output-file
Error: Unbound variable: open-binary-output-file
cyclone> open-binary-input-file
Error: Unbound variable: open-binary-input-file
cyclone> open-output-file
(primitive <primitive open-output-file>)
cyclone> open-input-file
(primitive <primitive open-input-file>)
```

Was: #337 

Tested: https://github.com/justinethier/cyclone/commit/8a115df5164a79961b1c8dcb47d3a4d29a478eb2

**Comment by justinethier** [comment]
These should always have been available to the compiler but they were not exported to the REPL / eval. Fixed.
