### ISSUE TITLE
eqv? does not compare numbers correctly

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#375]
`eqv?` procedure does not compare numbers correctly. 

R7RS states:

> obj1 and obj2 are both inexact numbers such that theyare numerically equal
> (in the sense of `=`) and they yield the same results (in the sense of `eqv?`)
> when passed as arguments to any other procedure that can be defined as a finite
> composition of Scheme's standard arithmetic procedures, provided it does not
> result in a NaN value.

thus, `(eqv? 0.0 0.0)` (zeroes with same sign) should be `#t`.

```
cyclone> (eqv? 0.0 0.0)
#f
cyclone> (= 0.0 0.0)
#t
```

It's same for exact numbers.

```
cyclone> (= 123456123456123456 123456123456123456)
#t
cyclone> (eqv? 123456123456123456 123456123456123456)
#f
```

(It seems Cyclone implements `eqv?` as `eq?`; although it is correct for the most of object types, R7RS requires numbers are handled specially at least.)

Tested: https://github.com/justinethier/cyclone/commit/8a115df5164a79961b1c8dcb47d3a4d29a478eb2

**Comment by justinethier** [comment]
Good catch. The logic seems simple enough, this is from Chibi:

    (define (eqv? a b) (if (eq? a b) #t (and (number? a) (equal? a b))))

Since our `eqv?` is already implemented in C it may be more convenient (and faster) to implement the same logic in our C runtime.

**Comment by justinethier** [comment]
Fixed on `master` and will be included in the next release.
