### ISSUE TITLE
atan procedure does not process 2 arguments correctly

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#376]
`(scheme complex)` implements `angle` procedure as:

```scheme
(define (angle z) (atan (imag-part z) (real-part z)))
```

but it seems `atan` does not handle two arguments correctly (just falls back to single argument `atan` silently).

C language has both variants of atan with different names, `atan` is for single argument version, `atan2` is for two arguments version.

tested: https://github.com/justinethier/cyclone/commit/8a115df5164a79961b1c8dcb47d3a4d29a478eb2

**Comment by justinethier** [comment]
This has been fixed on `master` and will be in the next release.
