### ISSUE TITLE
`if` always return something

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#377]
According to `R7RS` when there is no `alternate` form to an `if` (eg.: `(if #f #f)`) it should present an undefined behavior. But in Cyclone it always return something, which produces subtle bugs (to be shown in a pull request after this issue is fixed).

On Cyclone:
 ```scheme
cyclone> (if #f #f)
#f
cyclone> 
```
On Chibi (for example):
```scheme
> (if #f #f)
> 
```

@justinethier, is there an internal representation of `undefined` in Cyclone? I could not find it and also I could not find where `if`s are translated into C. If you point them out to me maybe I can fix this issue. 

Cheers,
Arthur

**Comment by justinethier** [comment]
@arthurmaciel Unfortunately there is no representation of `undefined` in Cyclone. Many other Schemes define a special type for void / undefined, and it does make things cleaner on the REPL.

This would first involve adding the type at the C layer, perhaps modeled after the EOF type (search for `eof_tag`). One of the compiler passes (I forget which but can find it) transforms `(if #f #f)` into `(if #f #f #f)` - it could be changed instead to `(if #f #f #undefined)`, though the reader would need to understand `#undefined`, the downstream compiler would probably need updates to finish compilation (perhaps just adding a case to `const?` and the `cgen` module, which generates the C code), and the interpreter would need to print nothing (this might be a change to `display` though). Mostly these should be little fixes across the code base.

I will need to spend more time looking into 378. Regardless this would be a good fix though. If you're interested I can help you make it; I also don't mind picking it up.

**Comment by arthurmaciel** [comment]
@justinethier, thanks for the detailed explanation!

I think I would take months to fix it all, due to my lack of knowledge of Cyclone internals, specially about the compilation scheme. So for the good of the Cyclone community I would prefer if you pick it up :)

**Comment by justinethier** [comment]
@arthurmaciel No worries. Don't mean to discourage you with the explanation, just wanted to include all the details I could think of up front to think it through, regardless of implementer. I will plan on working it :)

Let me try to find some time (hopefully later today) to look into the `for-each` issue and get back to you on that, to figure out which issue to prioritize.

**Comment by justinethier** [comment]
Merged back to `master`.
