### ISSUE TITLE
`for-each` does not produce `undefined` behavior and thus over-iterates

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#378]
On `icyc`: 

```scheme
cyclone> (for-each car '())
#f
cyclone> 
```
and on `chibi-scheme`:

```scheme
> (for-each car '())
> 
```

Also on `icyc`: 

```scheme
cyclone> (for-each (lambda (e) (display e)) '(1 2 3 4))
1234() ;; prints extra parenthesis
cyclone> 
```
and on `chibi-scheme`:

```scheme 
> (for-each (lambda (e) (display e)) '(1 2 3 4))
1234> 
```

Although `for-each` is explicitly defined in `base.sld`,  `transforms.sld` converts the expression into calls to `Cyc-for-each-loop-1` or `Cyc-for-each-loop-2`, depending on the arity given (see [here](https://github.com/justinethier/cyclone/blob/fa97a33bcf4a4ddbfd13a7d5fb79bd187dbe796d/scheme/cyclone/transforms.sld#L1125)). 

Although `for-each` should "return" `undefined`, both procedures return `'()` (it seems their basic structure was copied and pasted from the definition of `Cyc-map-loop-1` and `Cyc-map-loop-2` respectively). This extra `'()` is the culprit for a "over-iteration" of `for-each`. So removing the `'()` return value from these procedures should fix it, but debugging a bit more I found that `if` does not end with `undefined` when there is no `alternate` form to it (as in `(if #f 'never-reached)`). It always returns something, in this case `#f`. So when I remove the `'()` return value from both `Cyc-for-each-loop-1` or `Cyc-for-each-loop-2`, letting the `if` with only its `consequent` part, the example code turns into `1234#f`.

Waiting for issue #377 to be fixed.

**Comment by justinethier** [comment]
This should be fixed now on the `void-dev` branch.

**Comment by justinethier** [comment]
Merged to `master`.

**Comment by arthurmaciel** [comment]
Precise as always! Thanks, @justinethier!
