### ISSUE TITLE
read-char unexpectedly consumes entire port content

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#379]
`read-char` consumes entire port buffer which is not expected for file and buffered ports(e.g. `open-input-string` port).

```scheme
cyclone> (define p (open-input-string "one\ntwo\n"))
ok
cyclone> (read-char p)
#\o
cyclone> (read-line p)

```

The last `read-line` actually returns `#!eof` but due to #223 it exits instead.

tested: https://github.com/justinethier/cyclone/commit/22a68d10977da0e26e12356f2b560c609f045548

**Comment by justinethier** [comment]
Good catch and I agree this needs to be fixed but this will not be a quick turn-around.

It seems unlikely that the same port would be read using both `read-char` and `read-line` calls, but it could happen.

**Comment by justinethier** [comment]
Fixed to ensure `read-line` may be used in conjunction with other I/O functions to read from the same port. 

Thanks for the report @okuoku
