### ISSUE TITLE
write-string does not support 3rd argument or beyond

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#380]
R7RS `write-string` procedure requires to support 3rd or 4th argument to add `substring` feature in one call.

```scheme
cyclone> (write-string "abcd" (current-output-port) 0 2)
abcd
cyclone> (write-string "abcd" (current-output-port) 3)
abcd
```

tested: https://github.com/justinethier/cyclone/commit/22a68d10977da0e26e12356f2b560c609f045548

**Comment by justinethier** [comment]
Fixed
