### ISSUE TITLE
Not finding `(cyclone ...)` libraries on current master

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#386]
@justinethier, does your system reproduce this error?

```scheme
cyclone cyclone-winds.scm 
Error: Unable to open file: "/usr/local/share/cyclone/cyclone/match.sld" 
Call history:
scheme/base.sld:call/cc
scheme/base.sld:append
scheme/base.sld:foldl
scheme/base.sld:foldr
scheme/base.sld:foldl
scheme/base.sld:foldr
scheme/base.sld:foldl
scheme/base.sld:Cyc-for-each-loop-1
scheme/cyclone/libraries.sld:lib:check-system-path
```

After installing `cyclone-bootstrap` and `cyclone` from `master` today, the system can't `(import ...)` all libraries under `(cyclone ...)` as `match`, `test` etc. I couldn't find a commit that justifies this error, that's why I am wondering if my system is broken. 

Running `(import (cyclone match))` on `icyc` is enough to test.

**Comment by arthurmaciel** [comment]
My system was definitely broken.

**Comment by justinethier** [comment]
Thanks for confirming, hope it is not too painful to fix up :)

I completely uninstalled and rebuilt cyclone to double-check. Everything is working fine over here after a reinstall.
