### ISSUE TITLE
Using gcc 10.1 with cyclone results in multiple defintion linker errors

### ISSUE THREAD

**Issue by donaldsonjw** [justinethier/cyclone#388]
In gcc 10, gcc now defaults to compiling with the -fno-common compiler option enabled. This causes multiple definition linker errors for a number of symbols including _argc and _argv. It can be fixed by passing -fcommon to gcc.

**Comment by justinethier** [comment]
Thanks for the report @donaldsonjw ! Will see about getting a fix for this ASAP.

**Comment by justinethier** [comment]
Looks like we can fix the root problem instead of passing/not passing the -fcommon option. This works with gcc 10.1 on Arch Linux as well as in older versions of gcc on github's CI.

@donaldsonjw If you are able, can you confirm this fix works for you as well?

**Comment by donaldsonjw** [comment]
I can confirm it works for me. Thanks.
