### ISSUE TITLE
Huge '.c' file when compiling bitwise arithmetic code

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#393]
@justinethier, when I try to compile a port of Chibi's [md5 library](https://github.com/arthurmaciel/md5.git) the compiler takes a long time and produces a 7.8MB `md5.c` file with more than 150k lines of code.

You can reproduce it by running:

```
git clone https://github.com/arthurmaciel/md5.git
cd md5
cyclone-winds build-local ;; almost 2 minutes
cyclone-winds test-local
```

which yields and error when trying to `(md5 "")`

```
md5: !..
2 out of 3 (66.7%) tests passed in 0.0 seconds.
1 error (33.3%).
ERROR: (md5 "")
    ("Unable to open input memory stream" 22)Tests performed
```

Compiler times do not differ here between `gcc 9.3.0` and `clang 8.0.1`:

```
# gcc9
time CC=/usr/local/bin/gcc9 cyclone-winds build-local
# 126,81s user 
# 1,17s system 
# 107% cpu 
# 1:59,31 total

# clang
time cyclone-winds build-local 
# 125,62s user 
# 1,31s system 
# 108% 
# cpu 1:57,41 total
```

I need this package in order to port the [PostgreSQL one](https://github.com/ktakashi/r7rs-postgresql). But I am not sure I should add it considering its size. What do you think?

**Comment by justinethier** [comment]
The problem here is a massive explosion in program size during the CPS compilation phase. There is a LOT going on in `(md5 src)` including quite a few macro expansions. There may not be a good solution here. It may be more practical to implement the meat of this algorithm in C.

**Comment by arthurmaciel** [comment]
Thanks, @justinethier! I will accept the PR on MD5 package.
