### ISSUE TITLE
Isn't cond-expand working?

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#394]
@justinethier, when porting the PostgreSQL package I have faced the following problem. Is this the expected behavior? Am I missing something?

```scheme
(define-library (test)
  (export bar)
  (import (scheme base))
  (cond-expand
   ((library (srfi 19))
    (import (srfi 19))
    (define foo 1))
   (else
    (define foo 2)))
  (begin
    (define (bar)
      foo)))
```

```
$ cyclone test.sld
Error: (Unhandled expansion foo) 
Call history:
scheme/cyclone/util.sld:flatten
scheme/base.sld:Cyc-for-each-loop-2
scheme/eval.sld:_expand
scheme/cyclone/util.sld:const?
scheme/cyclone/primitives.sld:prim?
scheme/cyclone/util.sld:ref?
scheme/cyclone/util.sld:tagged-list?
scheme/base.sld:error
scheme/base.sld:raise
```

**Comment by arthurmaciel** [comment]
I realized  #291 deals with the same problem. Closing this.

**Comment by arthurmaciel** [comment]
For the record: I will remove all cond-expands for now.

**Comment by justinethier** [comment]
@arthurmaciel Good catch on both counts!

Sorry about this. I would like to fix it at some point as it would be very useful to have `cond-expand` at the library level, especially when writing libraries to support multiple Schemes.

That said, for our purposes in porting libraries to Cyclone, we don't need `cond-expand` in this context. I agree the best approach for now is to remove the `cond-expand`'s.
