### ISSUE TITLE
Test library produces opposite results

### ISSUE THREAD

**Issue by arthurmaciel** [justinethier/cyclone#395]
Looking at the code I can't understand why the opposite results are produced. I haven't tested other procedures from the library, except `test` itself.

```
$ icyc

cyclone> (import (cyclone test))
ok
cyclone> (test-assert #t)
xFAIL
cyclone> (test-assert #f)
.PASS
cyclone> (test-not #f)
xFAIL
cyclone> (test-not #t)
.PASS

$ chibi-scheme 
> (import (chibi test))
> (test-assert #t)
.PASS
> (test-assert #f)
xFAIL
> (test-not #f)
.PASS
> (test-not #t)
xFAIL
```

**Comment by arthurmaciel** [comment]
PS: I found this when trying to port a PostgreSQL package from a pure R7RS implementation with already provided tests.

**Comment by justinethier** [comment]
Weird. The strange this is, when compiled, the tests do return the expected results:

```
[justin@justin-pc Documents]$ cat test3.scm
(import
  (scheme base)
  (scheme write)
  (cyclone test))

(write (test-not #f))
(newline)

(write (test-not #t))
(newline)
[justin@justin-pc Documents]$ cyclone test3.scm
[justin@justin-pc Documents]$ ./test3
.PASS
xFAIL

```

**Comment by justinethier** [comment]
To follow-up on the previous comment, it seems this is likely an issue with the interpreter.

**Comment by justinethier** [comment]
The `(test-not #t)` macro is being expanded as follows:

```
;; Generated by compiler
    (test-run
      (lambda () #f)
      (lambda () (not #t))
      (cons (cons 'name #f)
            (cons (cons 'source (cons 'not (cons #t '())))
                  (cons (cons 'var-names '())
                        (cons (cons 'var-values (list))
                              (cons (cons 'assertion #t) '()))))))

;; Generated by interpreter
(test-run
  (lambda () #f)
  (lambda () (not #t))
  (cons (cons 'name$3 #f)
        (cons (cons 'source$5 (cons 'not (cons #t '())))
              (cons (cons 'var-names$6 '())
                    (cons (cons 'var-values$7 (list))
                          (cons (cons 'assertion$2 #t) '()))))))

```

It seems there is a problem specifically with the `assertion$2` identifier expanded by the interpreter. If we use `assertion` then the test fails as expected.

**Comment by justinethier** [comment]
Updated the interpreter to use the same macro expansion and identifier cleanup calls as the compiler. All of these tests now have the expected results.

**Comment by justinethier** [comment]
Added unit tests to ensure this is tested on an on-going basis for regressions. Closing.
