### ISSUE TITLE
Record-type accessors do not check if the passed record is of the appropriate type

### ISSUE THREAD

**Issue by ankar71** [justinethier/cyclone#402]
The easiest way to explain the error is with an example. Try this:

```
(define-record-type <point> (point x y) point? (x point-x) (y point-y))

(define-record-type <person> (person name surname) person? (name person-name) (surname person-surname))

(define point1 (point 1 2))
(define person1 (person "John" "Doe"))
```
And then this:
`(person-surname point1) ; this works and returns 2`

Obviously this is not the expected behavior.

Andreas

PS: I tested this with the currently latest version 0.19

**Comment by justinethier** [comment]
Thanks for the bug report @ankar71 ! 
Your example was very helpful as well.

This has been fixed on our main branch and will be included in the next release.
