### ISSUE TITLE
Update official Docker image?

### ISSUE THREAD

**Issue by andyvanee** [justinethier/cyclone#408]
I'm new to Cyclone and was a bit confused since I installed from the official docker image and tried out a few of the examples. I quickly ran into errors with the `call-scm-from-c` examples, and after some digging in the change log I discovered that those examples use features newer than the docker image supports.

I was able to copy <https://hub.docker.com/r/cyclonescm/cyclone/dockerfile> and update to `ENV CYCLONE_VERSION v0.20`. With this I am actually able to compile the files without errors (although I do get segfaults when I run them, which is probably a separate issue).

Is it possible to generate new Docker build tags when tagging releases? Thanks!

**Comment by justinethier** [comment]
Thanks for the feedback @andyvanee and sorry for the inconvenience there.

Everything is setup on docker.com but there is an error building the image:

```
Setting up tzdata (2020a-0ubuntu0.20.04) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring tzdata
------------------
Please select the geographic area in which you live. Subsequent configuration
questions will narrow this down by presenting a list of cities, representing
the time zones in which they are located.
1. Africa 4. Australia 7. Atlantic 10. Pacific 13. Etc
2. America 5. Arctic 8. Europe 11. SystemV
3. Antarctica 6. Asia 9. Indian 12. US
Geographic area:
Build canceled.
```

Will need to investigate further...

**Comment by lassik** [comment]
FWIW, `docker run -it schemers/cyclone` is now at version 0.20.

**Comment by andyvanee** [comment]
No problem!

I had the same issue with the docker install and fixed it with `DEBIAN_FRONTEND=noninteractive apt install -y ...`. This is my full Dockerfile for reference:

```Dockerfile
FROM ubuntu:latest

ENV CYCLONE_VERSION v0.20

RUN apt update -y && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    build-essential git rsync texinfo libtommath-dev libck-dev make gcc ca-certificates

RUN git clone https://github.com/justinethier/cyclone-bootstrap && cd cyclone-bootstrap && git fetch -a && git checkout ${CYCLONE_VERSION} && make && make install

CMD ["icyc"]
```

**Comment by justinethier** [comment]
Hey @andyvanee good timing! :)

I fixed it in the same manner, adding the line:

`
ARG DEBIAN_FRONTEND=noninteractive
`

Anyway, the official image works again and has been built, if you want to use it in the future. 
Thanks again for reporting this issue!

**Comment by andyvanee** [comment]
Awesome, thanks! 👍
