### ISSUE TITLE
Failing tests in git master

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#409]
Currently two tests fail when building our `:head` Docker image:

```
2 errors (6.7%).
ERROR: ...(match (make-employee "Bob" "Doctor") (($ employee n t) (lis...
(match "no matching pattern")(let () (define-record-type employee (make-employee name title) employee? (name get-name) (title get-title)) (match (make-employee "Bob" "Doctor") (($ employee n t) (list t n))))
ERROR: ...(match (make-employee "Bob" "Doctor") ((@ employee (title t)...
(match "no matching pattern")(let () (define-record-type employee (make-employee name title) employee? (name get-name) (title get-title)) (match (make-employee "Bob" "Doctor") ((@ employee (title t) (name n)) (list t n))))
Predicates: ...
3 out of 3 (100.0%) tests passed in 0.0 seconds.
Demo: ...
3 out of 3 (100.0%) tests passed in 0.0 seconds.
make: *** [Makefile:146: tests/match-tests] Error 1
```

**Comment by justinethier** [comment]
These tests work fine with a newer version of cyclone but it was broken a few versions ago. Are you sure you are running a recent version of cyclone? What version number do you get if you run `icyc` in this environment?

**Comment by justinethier** [comment]
@lassik Do you have a build log or any way to independently reproduce this? Without a bigger picture there is not much I can do on this end, since the tests are passing over here...

**Comment by lassik** [comment]
Nevermind, we may have built git master against an old version of cyclone-bootstrap. Bootstrapping from 0.21, all tests pass.

**Comment by justinethier** [comment]
Great, glad it is working now, and thanks for confirming @lassik

**Comment by lassik** [comment]
Np, sorry about the delay. `docker run -it schemers/cyclone:head` is now up to date with master (rebuilds of the container still have to be triggered manually; we need to figure out a system to do it automatically).

**Comment by lassik** [comment]
And `docker run -it schemers/cyclone` is now release 0.21.
