### ISSUE TITLE
Broken links on the 'Example Programs' section on landing page

### ISSUE THREAD

**Issue by Vitao18** [justinethier/cyclone#416]
Hi there,
The links on the 'Example Programs' section on the landing page are broken. I think they are pointing to the website instead of pointing to the Github code.
I would fix it but I couldn't find the code for the webpage here.

**Comment by justinethier** [comment]
Thanks for the report @Vitao18 ! All of the links should be fixed now.

For future reference the web site code is under the `gh-pages` branch.
