### ISSUE TITLE
results of numerator, denominator

### ISSUE THREAD

**Issue by hikmet517** [justinethier/cyclone#433]
In r7rs.pdf:
(numerator (/ 6 4)) => 3
(denominator (/ 6 4)) => 2

In cyclone:
(numerator (/ 6 4)) => 1.5
(denominator (/ 6 4)) => 1

Is this a bug or is it intentional?

**Comment by justinethier** [comment]
@hikmet517 good question. What is going on there is both of these functions are present but not fully implemented due to cyclone not having support for rational numbers (the rest of the numeric tower is implemented). I would like to add support for all of this at some point in the future.

**Comment by justinethier** [comment]
These functions have now been fully-implemented and will be included in the next release.
