### ISSUE TITLE
Synchronize latest winds with cyclone-bootstrap

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#436]
Now that the paths to our package manager have changed, it will be necessary to pull a new copy into bootstrap. We may want to make this a release in the short term to avoid issues with the Github URL changing.

**Comment by arthurmaciel** [comment]
Justin, could you please guide me on how to do it? Is there some docs on
it? Thanks!

Em sex, 22 de jan de 2021 11:36, Justin Ethier <notifications@github.com>
escreveu:

**Comment by justinethier** [comment]
@arthurmaciel Sure, we just need to compile winds using the latest version of cyclone and copy the generated `.c` files into the appropriate locations under the `winds` directory in cyclone-bootstrap. Once that's done we will also need to rename the program to `winds.c` and modify the makefile to use `winds` instead of `cyclone-winds`.

Would you like to make a pull request for this?

Longer-term there probably should be a script to automate this process, but that is a separate issue :)

**Comment by arthurmaciel** [comment]
@justinethier, I followed the steps. But I am not sure I understood the task correctly: should I have sync'ed `cyclone-bootstrap` or `cyclone`? I've done it to `cyclone-bootstrap` only (please see [here](https://github.com/justinethier/cyclone-bootstrap/pull/15)).

**Comment by justinethier** [comment]
@arthurmaciel Looks great, thanks! I overlooked that the `winds` directory would conflict with the new `winds` executable name, so I moved the source files to `tools/winds`.
