### ISSUE TITLE
Minor GC error in windows msys build

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#448]
Noticed the following error in last night's windows msys2 CI build:

```
make unit-tests
make[1]: Entering directory '/d/a/cyclone-bootstrap/cyclone-bootstrap'
./cyclone unit-tests.scm && ./unit-tests
gc_move: bad tag obj=0xffff5950 obj.tag=255
make[1]: *** [Makefile:140: unit-tests] Error 1
```

Have not seen any other cases of this recently and am not aware of an issue with the minor GC moving objects. Will need to keep an eye on this to see if it reoccurs, and to find a root cause.

**Comment by arthurmaciel** [comment]
@justinethier, I am on Linux but I faced a similar error:

```Scheme 
(import (scheme base)
        ;; (scheme write)
        )

(define (fib n)
  (if (< n 2)
      n
      (+ (fib (- n 1)) (fib (- n 2)))))

(display (fib 20))
```

On `v0.25`:
```Shell
cyclone /tmp/b.scm
Error: Unbound variable(s): 
(display)
``` 

On `v0.26`:
```Shell
cyclone /tmp/b.scm
gc_move: bad tag obj=0x7fffc6f3f3c0 obj.tag=145
``` 

If I uncomment `(scheme write)`, both versions compile and run ok.

**Comment by justinethier** [comment]
Thanks for the head's up @arthurmaciel ! There a good chance this was broken by a recent change. I'll see if I can reproduced here.

Just curious, do you see this error each time you recompile the program or is the problem intermittent?

**Comment by arthurmaciel** [comment]
@justinethier, I see this error every single time I recompile the program.

**Comment by justinethier** [comment]
The issue here is that calls in `cyclone.scm` were modified to include an extra parameter to support changes to the scheme libraries, but a compiled `cyclone.c` was never checked into the bootstrap repo. So we had a low-level C issue! 

The compiled file has been checked in and I am no longer seeing this crash. 

@arthurmaciel Please let me know if you do happen to see any more instances of this with a fresh installation from bootstrap master.
