### ISSUE TITLE
{armhf, armv7, ppc64le}: In fixnum/bitwise test case test-167 fails

### ISSUE THREAD

**Issue by nmeum** [justinethier/cyclone#475]
On [Alpine Linux](https://alpinelinux.org) Edge the cyclone-0.31.0 test suite fails on the armhf, armv7 and ppc64le architecture. It passes on x86_64, x86 and aarch64 so it seems to be an architecture-specific problem.  The error message looks as follows:

```
./cyclone -I . -COPT '-Iinclude' -CLNK '-L.' -I . tests/srfi-143-tests.scm
./tests/srfi-143-tests
fixnum: 
    fixnum/arithmetic: ..........................................
    42 out of 42 (100.0%) tests passed in 0.0 seconds.
    fixnum/bitwise: ..........................x...............................
    ...............................
    88 out of 89 (98.9%) tests passed in 0.0 seconds.
    1 failure (1.1%).
    FAIL: test-167
        expected #t but got #f
(fxbit-set? 1000 -1)
130 out of 131 (99.2%) tests passed in 0.0 seconds.
```

The buildlogs can be found here:

1. armhf:  [alpine-edge-armhf-cyclone-0.31.0.txt](https://github.com/justinethier/cyclone/files/6949548/alpine-edge-armhf-cyclone-0.31.0.txt)
2. armv7:  [alpine-edge-armv7-cyclone-0.31.0.txt](https://github.com/justinethier/cyclone/files/6949549/alpine-edge-armv7-cyclone-0.31.0.txt)
3. ppc64le: [alpine-edge-ppc64le-cyclone-0.31.0.txt](https://github.com/justinethier/cyclone/files/6949550/alpine-edge-ppc64le-cyclone-0.31.0.txt)

As you can see, all other tests pass. Would be nice to also get this single remaining test to pass as well. If you need any further information to debug/reproduce this, let me know.

**Comment by justinethier** [comment]
Thanks for the report @nmeum 

This should be fixed on the `master` branch by https://github.com/justinethier/cyclone/commit/fa58b9d538bab5c87fc2040e561b3eca31acbe39 - would it be possible for you to rerun the tests to confirm?

**Comment by nmeum** [comment]
I can confirm that the commit you referenced fixes the build failure on the mentioned architectures. Thanks a lot! Closing this.

**Comment by justinethier** [comment]
@nmeum No problem, thanks for confirming :)
