### ISSUE TITLE
installing on cyclone with brew doesn't work properly

### ISSUE THREAD

**Issue by bentxt** [justinethier/cyclone#485]
when installing cyclone with `brew`, the `cyclone` compiler doesn't work properly. When importing the most basic libraries for a simple "hello world", there are problems with the library system:

```
$ cat hello.ss
(import (scheme base)
        (scheme write))

(write "hello")
```

```
$ cyclone hello.ss

Error: Unable to open file:
"/usr/local/share/cyclone/scheme/cyclone/common.sld"
```

Under this directory "/usr/local/share/cyclone/scheme/cyclone" there are only .so files the .sld files live under brews installation directory of /usr/local/Cellar/cyclone. Prepending the correct path with "-I" doesn't help.

**Comment by justinethier** [comment]
Thanks for the report @bentxt - let me take a closer look at this.

**Comment by justinethier** [comment]
OK, this should be working much better now. 

Can you please try `brew` again when you have a moment?

**Comment by bentxt** [comment]
yes it does work!

thanks a lot!
