### ISSUE TITLE
`assv` seems implemented as `assq`

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#490]
Tested: https://github.com/justinethier/cyclone/tree/cf66cf1057fcd687cc42d4d7dcaeeef00cba089b

It seems `assv` implemented as `assq`.

```
cyclone> (define a 0.0)
ok
cyclone> (assoc a (list (list a)))
(0.0)
cyclone> (assoc 0.0 (list (list a)))
(0.0)
cyclone> (assv a (list (list a)))
(0.0)
cyclone> (assv 0.0 (list (list a)))
#f
```

Did you mean `assv` here? https://github.com/justinethier/cyclone/blob/6ffd229dcdd1b74e77bc3f33d245efc4c340edf6/runtime.c#L5395

(and maybe `memvp` here https://github.com/justinethier/cyclone/blob/6ffd229dcdd1b74e77bc3f33d245efc4c340edf6/runtime.c#L5409 )

xref: #375

**Comment by justinethier** [comment]
Good catch, let me take a look.

**Comment by justinethier** [comment]
Thanks for the report @okuoku. This is now fixed on our primary branch in GitHub.
