### ISSUE TITLE
Cyclone says 1.5 is an odd number

### ISSUE THREAD

**Issue by jpellegrini** [justinethier/cyclone#501]
Hello!

I just noticed Cyclone returns this:

```scheme
(odd? 1.5)  => #t
(even? 1.5) => #f
```

Most Schemes signal an error on both. I would guess that it would be ok to answer `#f` for both... But It's currently saying 1.5 is odd.  :)

**Comment by justinethier** [comment]
Good catch @jpellegrini! Thanks for the bug report. 

Cyclone will now throw an error if a non-integer is passed to these functions.
