### ISSUE TITLE
abs of complex number

### ISSUE THREAD

**Issue by lassik** [justinethier/cyclone#506]
`(abs -3-4i) => 3.0`

Returns abs of the real part, discards the imaginary part.

**Comment by lassik** [comment]
Via https://github.com/schemedoc/surveys/pull/50 cc @jpellegrini

**Comment by jpellegrini** [comment]
As @lassik said somewhere else, if you interpret R7RS as saying "abs" only applies to reals, it's not strictly wrong -- it would be an error, and in such situation the implementation may do anything it wants.
But it would be nice to return something useful, like the complex norm! :grin:

**Comment by justinethier** [comment]
Thanks for the report! For now, Cyclone will return an error in this case.
