### ISSUE TITLE
Cyclone doesn't read `-inf.0` as negative (?)

### ISSUE THREAD

**Issue by jpellegrini** [justinethier/cyclone#511]
```scheme
cyclone> -inf.0 
inf.0
cyclone> (= -inf.0 +inf.0)
#t
```

**Comment by jpellegrini** [comment]
But it seems to be specific to the reader, since it does represent infinities properly:

```scheme
(- +inf.0) => -inf.0
```

**Comment by justinethier** [comment]
Thanks for the bug report! 

Cyclone will now properly distinguish between positive and negative infinity.
