### ISSUE TITLE
`truncate-quotient` should return exact number where possible

### ISSUE THREAD

**Issue by okuoku** [justinethier/cyclone#519]
Tested: https://github.com/justinethier/cyclone/commit/1d775c5a752048466f19c5f3f67706bf3678a555

```scheme
cyclone> (truncate-quotient 5 2)
2.0
```

Per R7RS, `truncate-quotient` should return exact result if input was exact integers. R7RS provides example as following:

```scheme
(truncate/ -5 -2) => 2 -1
(truncate/ -5.0 -2) => 2.0 -1.0
```

**Comment by justinethier** [comment]
This has been fixed on `master` branch. Thanks for the report!
