### ISSUE TITLE
Allow apply to accept multiple arguments

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#54]
From the report, `apply` should be able to accept many list args:

    (apply proc arg1 ... args)

> The apply procedure calls `proc` with the elements of the list `(append (list arg1 ... ) args)` as the actual arguments.

**Comment by jasonmacduffie** [comment]
Actually it is not specifically many list args. For example, this works:

(apply + 1 2 3 '(4 5)) => 15

**Comment by justinethier** [comment]
Good catch, thanks.

**Comment by justinethier** [comment]
This is now fixed on the `apply2-dev` branch.
