### ISSUE TITLE
Exposing the supported SRFIs trough (features)

### ISSUE THREAD

**Issue by Retropikzel** [justinethier/cyclone#543]
These Scheme implementations have supported SRFIs listed on the (features) list.

- Gauche
- Guile
- Kawa
- Stklos
- Gambit
- Chicken

Would it be possible to expose them in Cyclone too?

It would help when writing portable code that might depend on SRFI, but fall back on (mayber slower) portable implementation.

**Comment by Retropikzel** [comment]
Nevermind. My bad for not reading the R7RS better.

Listed implementations expose the SRFIs with cond-expand like this:
`(cond-expand (srfi-N ...) (else ...))`

and I expected Cyclone to behave the same, but Cyclone uses the form:
`(cond-expand ((library (srfi N)) ...) (else ...))`

**Comment by justinethier** [comment]
No worries, thanks for the bug report and following-up!
