### ISSUE TITLE
Complex number support

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#55]
Support should be added for complex numbers. This could be done using C99 but it might be more flexible if it could be done without `complex.h`.

**Comment by kozross** [comment]
Given that you rely on C99 for parts of Cyclone's core code, I'm not certain why you object to ``complex.h`` as a solution. Granted, if portability to Windows were a serious concern, I'd understand, but from what I can tell, this isn't a high priority.

**Comment by justinethier** [comment]
That's true, at this point it makes sense to use `complex.h`. That should be the starting point for a complex number implementation. Maybe in a release or two this can be integrated.

**Comment by kozross** [comment]
I agree. I reckon that having bignums first would be a better move - especially since I want them badly. 😜

**Comment by justinethier** [comment]
Merged to master.
