### ISSUE TITLE
Library syntax support (r7rs section 5.6)

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#61]
The following forms are supported:
    - export
    - import
    - begin
    - include
    - rename

The following are not yet supported:
    - cond-expand
    - include-ci

In addition, these are non-standard but would be nice to have:
    - export-all

**Comment by kozross** [comment]
``cond-expand`` is partially supported now (I just had it work fine, as long as it was within ``define-library``). It doesn't work outside of it (as per #154).

**Comment by justinethier** [comment]
`export-all` will not be supported at this time, and `include-ci` is not useful without unicode support, which will be dealt with elsewhere. Closing this issue.
