### ISSUE TITLE
Add a match library

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#90]
At some point it would be nice to add a library to do pattern matching.

**Comment by ofosos** [comment]
I tried compiling irregex. There are two problems:

Library include:

  - I check out irregex.git into an irregex directory
  - try `cyclone irregex.sld`
  - it complains about 'chibi/irregex.scm` not found
 
The sld contains an `(import "irregex.scm)`. I'll look this up in R7RS, but this seems to be somewhat broken. However, simply checking out irregex.git into chibi solves the problem.

The tests (`test-irregex.scm`) bail on an invalid escape sequence in a string "\t".

cyclone> (display "a\tb")
Error: Error (line 1, char 10): invalid escape character [t] in string 
cyclone> Error: Unbound variable b 
cyclone> 

Where can I look to fix this up?

**Comment by justinethier** [comment]
Take a look at this `cond` - there is no clause for tab, and probably other characters as well:

https://github.com/justinethier/cyclone/blob/master/scheme/read.sld#L479

**Comment by ofosos** [comment]
Ok, that cond seems to work, but now I get stuff like literal tab characters inserted into my C source code. That won't work. Is there some nice way to fix it? Cyc_display doesn't seem to be the best way.

**Comment by justinethier** [comment]
I should have been more specific with this issue - I was thinking about a match library like http://synthcode.com/scheme/match.scm

Regular expressions are still useful, though.

**Comment by justinethier** [comment]
You can try using `write`. With the latest code on master escaped char sequences are preserved (EG "\t") instead of being expanded into literal characters.

**Comment by ofosos** [comment]
Hmm, irregex compiles but when I do some tests, it segfaults or throws an error.

Specifically doing (display (irregex "foobar" 'i)) simply segfaults. I'm not that familiar with the standard anymore, but I suppose 'display should output something sane for every input. What's the best way to debug this?

**Comment by ofosos** [comment]
Hmm, interesting match.scm compiles with cyclone only partially. After importing (scheme base) it generates c files but the c compiler barfs. The very last closure output has a missing semicolon. I'll try to investigate further, when I'm home.

**Comment by justinethier** [comment]
Interesting, do you know what ` (irregex "foobar" 'i)` is returning? Can you reproduce the segfault by passing that input directly to `display`?

I agree that `display` - and really, the entire runtime - should never segfault. Here are some instructions for debugging: https://github.com/justinethier/cyclone/blob/master/docs/Development.md#debugging-the-runtime

**Comment by justinethier** [comment]
Regarding `match.scm` - see https://github.com/justinethier/cyclone/issues/101 for what is going on. I tried adding a `write` at the end of the program and it actually finished compiling and created a working executable, although compilation took forever, probably due to all the `define-syntax` macros.

I haven't actually tested yet to see if matching works, though.

**Comment by ofosos** [comment]
Ok, that looks good. I'll have some quiet time during the weekend. Do you mind if I write a proper .sld for match.scm? I'll see if emacs can take some of the work off my hand.

What are your plans, should the matcher be incorporated into the base system? If so, under what namespace?

I'll also try and write some basic unit tests.

**Comment by ofosos** [comment]
Interesting. (irregex ..) returns a vector. That vector is fine until i dereference element 6 and try to display it. I tried the following program:

(import (chibi irregex) (scheme write) (scheme base) (srfi 18))

;(display (irregex-search "foobar" "abcFOOBARdef"))
(let ((x (irregex "foobar")))
  (let ((x (vector-ref x 6)))
    (display (number? x))
    (display (pair? x))
    (display (string? x))
    (display (list? x))
    (display (record? x))
    (display (symbol? x))
    (display (procedure? x))
    (display (boolean? x))
    (display (null? x))
    (display (mutex? x))))

This works and outputs: #f #f #f #f #f #f #f #f #f #f (spaces added)

Now I add a (display x) into the inner let. Bam it segfaults:

Thread 1 "test" received signal SIGSEGV, Segmentation fault.
0x00000000006aa2ef in Cyc_display (x=0x7ffffffb6270, port=0x7ffff76a7600 <_IO_2_1_stdout_>) at runtime.c:754
754         for (tmp = cdr(x); tmp && ((closure) tmp)->tag == pair_tag; tmp = cdr(tmp)) {
(gdb) p x  
$1 = (object) 0x7ffffffb6270
(gdb) p ((list)x)->tag
$2 = 14 '\016'
(gdb) p ((list)x)->pair_car
$3 = (object) 0xd
(gdb) p ((list)x)->pair_cdr
$4 = (object) 0xd

I see how this segfaults, but I've no idea how we get to this cons (??). I'll investigate further and report back (tomorrow).

**Comment by justinethier** [comment]
Sounds good about match. I have been placing non-standard libraries under `scheme/cyclone` so `(scheme cyclone match)` would be a good place to put it for now. 

I'm not sure if it will stay in core longer-term, though. Especially if it ends up taking a long time to compile, it may make sense to split it off and put it in a new library repo.

**Comment by justinethier** [comment]
OK, I see how `display` could segfault on an improper list, and that is now fixed with the above change. But I don't understand how `x` could be a pair but `(pair? x)` is false?? Anyway, you can try testing with this fix - hopefully it will actually display `x` which might help explain what is going on.

**Comment by ofosos** [comment]
Ok that fixed that particular occurance.

Try doing
`  (display "foobar" newline)
`

**Comment by justinethier** [comment]
Now you're having fun :)
Its important to plug these holes. This one at least won't segfault now.

**Comment by ofosos** [comment]
Irregex is now compiling and I don't get errors from the invocation, after debugging some more. It is however not working, after I switched off unicode support and changed some invocations of apply. I'll have to look into that, I don't think apply is called for in that particular instance, but I'm not sure if this might be a bug in Cyclone, let's see if I can get it working tomorrow.

**Comment by justinethier** [comment]
Integrating a match library on the `macro-rename-dev` branch. This is looking promising for the compiler though there are still problems with the interpreter.
