### ISSUE TITLE
Investigate concurrency based on Erlang's model

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#95]
EG:  see the Termite and Hardwood eggs

**Comment by justinethier** [comment]
Also consider looking into: Concurrent ML

Also: share-nothing threads with mailboxes

**Comment by justinethier** [comment]
And communicating sequential processes (CSP): 
http://www.usingcsp.com/

**Comment by arthurmaciel** [comment]
Is this Issue still relevant or is [`(cyclone concurrent)`](http://justinethier.github.io/cyclone/docs/api/cyclone/concurrent) is enough?

**Comment by justinethier** [comment]
@arthurmaciel That's a good question, I am not sure... let me look into this one a bit more before closing.

**Comment by justinethier** [comment]
Closing this now that we have `(cyclone concurrent)`. If there is an interest later on in a particular area (such as CSP) then a ticket/project/etc can be opened specifically focused on that topic.
