### ISSUE TITLE
cyclone-bootstrap installation

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#97]
With the recent fixes to support Arch Linux packaging, it may no longer be necessary to have a separate install.sh script. It would be nice if this could be done by `make install` instead. Failing that, it still might be a good idea to take `sudo` out of the install script, in case someone wants to install somewhere locally like a home directory, where superuser permissions are not desirable.

**Comment by ofosos** [comment]
See PR#2 of cyclone-bootstrap, is that what you had in mind?

**Comment by ofosos** [comment]
Hmm, I'm not sure how makepkg in Arch works, but I thinks it runs make and then chroots and runs make intall. With this change you could just skip the initial make stage and do everything during the installation step. Have to look at your package script.

**Comment by justinethier** [comment]
Thanks but I think there may be a little more work to do here. The makepkg script runs all of the `make` commands and then runs the `make install` commands. I wanted to divide everything up so that only the installation commands would need to execute with superuser privileges (if installing to a system directory, of course). That way there are no build artifacts (obj files, etc) owned by root. It should be possible do to this by changing CFLAGS to look in the local directory for headers/libraries, but then there needs to be a separate CFLAGS for the compiler commands invoked by cyclone.

Anyway, I was going to try to find some time to look into this later today. You're certainly welcome to it as well :)

**Comment by ofosos** [comment]
Hmm, you could add -L. to the CFLAGS, this would however fail building icyc in one go with the compiler.

**Comment by ofosos** [comment]
The other option is to pimp the pkg file and let it do everything in a chroot environment. I.e. doing an incremental bootstrap. Installing everything within the chroot, then leaving it and letting makepkg tar it all up.

**Comment by justinethier** [comment]
Modified the cyclone-bootstrap makefile to build everything using the local directory. In order to do so, the CFLAGS from Makefile.config need to be branched to use local CFLAGS to build cyclone and another set of COMP_CFLAGS to be used when `cyclone` is invoked.
